// ---------------------------------------------------------------- language (Arabic / English)
let LANG=(()=>{try{const v=localStorage.getItem(KEY+"-lang");if(v==="ar"||v==="en")return v}catch(e){}return /^ar/i.test(navigator.language||"")?"ar":"en"})();
function applyLang(){document.documentElement.lang=LANG;document.documentElement.dir=LANG==="ar"?"rtl":"ltr"}
const MON_AR=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
const AR={
"VAT Inspection Desk":"مكتب الفحص الضريبي","Overview":"نظرة عامة","Your data":"بياناتك","Reconciliations":"المطابقات","Prepare":"التحضير",
"Dashboard":"لوحة المتابعة","Company & period":"المنشأة والفترة","Trial balance":"ميزان المراجعة","VAT returns":"الإقرارات الضريبية","Sales register":"سجل المبيعات","Purchase register":"سجل المشتريات","Payments to ZATCA":"المدفوعات للهيئة","Sales by VAT box":"المبيعات حسب خانات الإقرار","Revenue vs returns":"الإيرادات مقابل الإقرارات","Output VAT":"ضريبة المخرجات","Input VAT":"ضريبة المدخلات","VAT account & penalties":"حساب الضريبة والغرامات","Document checklist":"قائمة المستندات","Inspection guide":"دليل الفحص",
"Your figures stay in this browser. Nothing is uploaded or sent anywhere.":"تبقى أرقامك في هذا المتصفح فقط، ولا يتم رفع أو إرسال أي شيء.",
"Example figures.":"أرقام توضيحية.","January 2025 is filled in with sample data so you can see how everything ties out.":"شهر يناير 2025 معبأ ببيانات تجريبية لتوضيح كيفية تطابق الأرقام.","Import my Excel workbook":"استيراد ملف Excel الخاص بي","Clear example data":"مسح البيانات التوضيحية",
"Remove all data (example or your own) and start with empty tables? Company settings are kept.":"حذف جميع البيانات (التوضيحية أو الخاصة بك) والبدء بجداول فارغة؟ سيتم الاحتفاظ بإعدادات المنشأة.","Clear all data":"مسح جميع البيانات","Cancel":"إلغاء","All tables cleared":"تم مسح جميع الجداول",
"Select all and copy (Ctrl+C), then paste into Excel.":"حدد الكل وانسخ (Ctrl+C)، ثم الصقه في Excel.","Close":"إغلاق","Copied. Paste it into Excel.":"تم النسخ. الصقه في Excel.",
"This data is too large to keep in the browser. It stays here until you close the page.":"حجم البيانات كبير جداً لحفظه في المتصفح، وستبقى متاحة حتى تغلق الصفحة.",
"The Excel reader didn't load. Check your connection and reload, or paste the data instead.":"لم يتم تحميل قارئ Excel. تحقق من الاتصال وأعد تحميل الصفحة، أو الصق البيانات بدلاً من ذلك.",
"That file couldn't be read. Save it as .xlsx and try again.":"تعذرت قراءة الملف. احفظه بصيغة ‎.xlsx وحاول مرة أخرى.",
"This isn't the VAT Inspection Pack workbook. Use the Import button on each table instead.":"هذا ليس ملف حزمة الفحص الضريبي. استخدم زر الاستيراد في كل جدول بدلاً من ذلك.","Workbook imported":"تم استيراد الملف",
"Add row":"إضافة صف","Import from Excel / CSV":"استيراد من Excel / CSV","Show only rows with exceptions":"عرض الصفوف التي بها ملاحظات فقط","Show all rows":"عرض جميع الصفوف","Copy table":"نسخ الجدول","Clear this table":"مسح هذا الجدول",
"Tip: copy a block of cells from Excel and paste into any cell here. Rows are added automatically. Dates can be dd/mm/yyyy or yyyy-mm-dd.":"نصيحة: انسخ مجموعة خلايا من Excel والصقها في أي خلية هنا، وستُضاف الصفوف تلقائياً. يمكن كتابة التواريخ بصيغة dd/mm/yyyy أو yyyy-mm-dd.",
"No rows with exceptions.":"لا توجد صفوف بها ملاحظات.","No rows yet. Paste from Excel, import a file, or add a row.":"لا توجد صفوف بعد. الصق من Excel أو استورد ملفاً أو أضف صفاً.","Delete row":"حذف الصف","Delete every row in this table?":"حذف جميع صفوف هذا الجدول؟","Delete rows":"حذف الصفوف",
"Account code":"رمز الحساب","Account name":"اسم الحساب","FS class":"تصنيف القوائم المالية","VAT mapping":"التصنيف الضريبي","Opening balance":"الرصيد الافتتاحي","Total movements":"إجمالي الحركات","Closing balance":"الرصيد الختامي",
"Invoice date":"تاريخ الفاتورة","Invoice no":"رقم الفاتورة","Document type":"نوع المستند","Customer":"العميل","Customer VAT no":"الرقم الضريبي للعميل","Customer type":"نوع العميل","VAT category":"الفئة الضريبية","Net (SAR)":"الصافي (ريال)","VAT (SAR)":"الضريبة (ريال)","E-invoice UUID":"المعرّف الفريد للفاتورة الإلكترونية","On FATOORA?":"مُبلّغة في فاتورة؟","GL account":"حساب الأستاذ","Export / zero-rate evidence":"إثبات التصدير / النسبة الصفرية","Period":"الفترة","Expected VAT":"الضريبة المتوقعة","VAT difference":"فرق الضريبة","Exceptions":"الملاحظات",
"Supplier invoice no":"رقم فاتورة المورد","Supplier":"المورد","Supplier VAT no":"الرقم الضريبي للمورد","Country":"الدولة","Expense nature":"طبيعة المصروف","Valid tax invoice?":"فاتورة ضريبية صحيحة؟","Claimed in return?":"مخصومة في الإقرار؟","Customs decl. (Bayan)":"البيان الجمركي","VAT claimed":"الضريبة المخصومة","Defensible VAT":"الضريبة القابلة للدفاع عنها","VAT at risk":"الضريبة المعرضة للرفض",
"Period # (0 = prior)":"رقم الفترة (0 = سابقة)","Payment date":"تاريخ السداد","SADAD / reference":"سداد / المرجع","Amount (SAR, refunds −)":"المبلغ (ريال، المستردات بالسالب)","Notes":"ملاحظات","Due date":"تاريخ الاستحقاق","Days late":"أيام التأخير","Months late":"أشهر التأخير","Est. penalty":"الغرامة التقديرية","Prior period":"فترة سابقة",
"Date outside audit periods":"التاريخ خارج فترات الفحص","No VAT category":"لا توجد فئة ضريبية","VAT ≠ 15% × net":"الضريبة ≠ 15% × الصافي","Invalid or missing customer VAT no":"الرقم الضريبي للعميل غير صحيح أو مفقود","Not reported/cleared on FATOORA":"غير مُبلّغ عنها أو غير معتمدة في فاتورة","Zero-rate/export evidence missing":"إثبات النسبة الصفرية أو التصدير مفقود","Credit note should be negative":"يجب أن يكون الإشعار الدائن بالسالب","Simplified invoice to VAT-registered B2B":"فاتورة مبسطة لمنشأة مسجلة في الضريبة","Unknown VAT category":"فئة ضريبية غير معروفة","Invalid or missing supplier VAT no":"الرقم الضريبي للمورد غير صحيح أو مفقود","VAT claimed without a valid tax invoice":"ضريبة مخصومة دون فاتورة ضريبية صحيحة","Blocked input VAT claimed":"خصم ضريبة مدخلات غير قابلة للخصم","Customs declaration no missing":"رقم البيان الجمركي مفقود","Reverse charge used for a local supplier":"تطبيق الاحتساب العكسي على مورد محلي","VAT claimed on a non-taxable category":"خصم ضريبة على فئة غير خاضعة",
"Standard 15% (Box 1)":"النسبة الأساسية 15% (خانة 1)","Citizens - Healthcare/Education (Box 2)":"المواطنون - صحة/تعليم (خانة 2)","Zero-rated domestic (Box 3)":"محلية بنسبة صفر (خانة 3)","Export (Box 4)":"صادرات (خانة 4)","Exempt (Box 5)":"معفاة (خانة 5)","Out of scope":"خارج النطاق",
"Standard 15%":"النسبة الأساسية 15%","Citizens - Healthcare/Education":"المواطنون - صحة/تعليم","Zero-rated domestic":"محلية بنسبة صفر","Export":"صادرات","Exempt":"معفاة",
"Standard domestic 15% (Box 7)":"محلية بالنسبة الأساسية 15% (خانة 7)","Import - VAT paid at customs (Box 8)":"استيراد - ضريبة مدفوعة في الجمارك (خانة 8)","Import - Reverse charge (Box 9)":"استيراد - احتساب عكسي (خانة 9)","Zero-rated purchase (Box 10)":"مشتريات بنسبة صفر (خانة 10)","Exempt purchase (Box 11)":"مشتريات معفاة (خانة 11)","Out of scope / Not reported":"خارج النطاق / غير مُقر عنها",
"Revenue - Out of scope / Other income":"إيرادات خارج النطاق / إيرادات أخرى","VAT Payable / Settlement":"ضريبة مستحقة / تسوية","Not VAT relevant":"غير متعلق بالضريبة",
"Tax Invoice":"فاتورة ضريبية","Simplified Tax Invoice":"فاتورة ضريبية مبسطة","Credit Note":"إشعار دائن","Debit Note":"إشعار مدين",
"B2B - VAT registered":"منشأة - مسجلة في الضريبة","B2B - Not registered":"منشأة - غير مسجلة","B2C - Individual":"فرد (مستهلك)","Government":"جهة حكومية",
"General business expense":"مصروف تشغيلي عام","Capital asset":"أصل رأسمالي","Entertainment / hospitality (blocked)":"ترفيه / ضيافة (غير قابلة للخصم)","Motor vehicle - private use (blocked)":"سيارة - استخدام شخصي (غير قابلة للخصم)","Staff personal benefit (blocked)":"منفعة شخصية للموظفين (غير قابلة للخصم)","Other non-business (blocked)":"أخرى غير تجارية (غير قابلة للخصم)",
"Yes":"نعم","No":"لا","Asset":"أصول","Liability":"التزامات","Equity":"حقوق ملكية","Revenue":"إيرادات","Expense":"مصروفات",
"Not started":"لم يبدأ","In progress":"قيد التنفيذ","Ready":"جاهز","Submitted":"تم التسليم","N/A":"لا ينطبق","Monthly":"شهري","Quarterly":"ربع سنوي",
"These settings drive every period, due date and check in the app.":"تحدد هذه الإعدادات جميع الفترات وتواريخ الاستحقاق والفحوصات في التطبيق.","Company name":"اسم المنشأة","VAT registration number":"الرقم الضريبي","15 digits, starts and ends with 3.":"15 رقماً، يبدأ وينتهي بالرقم 3.","Valid format":"صيغة صحيحة","Invalid format":"صيغة غير صحيحة","Commercial registration no":"رقم السجل التجاري","Start of the year under inspection":"بداية السنة محل الفحص","The first day of a month. Periods are generated from this date.":"أول يوم من الشهر. يتم إنشاء الفترات بدءاً من هذا التاريخ.","Filing frequency":"دورية تقديم الإقرار","Monthly if taxable supplies exceed SAR 40 million a year, otherwise quarterly.":"شهري إذا تجاوزت التوريدات الخاضعة 40 مليون ريال سنوياً، وإلا ربع سنوي.","Standard VAT rate (%)":"نسبة الضريبة الأساسية (%)","15% since 1 July 2020.":"15% منذ 1 يوليو 2020.","Rounding tolerance (SAR)":"حد فروق التقريب (ريال)","Differences up to this amount count as matched.":"الفروق حتى هذا المبلغ تعتبر مطابقة.","Penalty calculation date":"تاريخ احتساب الغرامات","Usually today or the date of the ZATCA notice.":"عادةً تاريخ اليوم أو تاريخ إشعار الهيئة.","Late payment penalty (% per month or part)":"غرامة التأخر في السداد (% عن كل شهر أو جزء منه)","VAT Law Art. 43.":"المادة 43 من نظام ضريبة القيمة المضافة.","Incorrect return penalty (% of the difference)":"غرامة الإقرار الخاطئ (% من الفرق)","VAT Law Art. 42. Indicative.":"المادة 42 من النظام. تقديرية.","Tax periods":"الفترات الضريبية","Start":"البداية","End":"النهاية","Return & payment due":"موعد الإقرار والسداد","Data":"البيانات","Import the VAT Inspection Pack workbook":"استيراد ملف حزمة الفحص الضريبي","Clear all tables":"مسح جميع الجداول","Load example data":"تحميل البيانات التوضيحية",
"Import reads the Excel workbook from earlier (Setup, TB_Monthly, VAT_Returns, Sales_Register, Purchase_Register, ZATCA_Payments, Checklist) and replaces what's here.":"يقرأ الاستيراد ملف Excel الخاص بالحزمة (Setup و TB_Monthly و VAT_Returns و Sales_Register و Purchase_Register و ZATCA_Payments و Checklist) ويستبدل البيانات الحالية.","Replace everything with the example data?":"استبدال جميع البيانات بالبيانات التوضيحية؟","Load example":"تحميل المثال",
"Opening balance plus the net movement for each month. Debits positive, credits negative. Give every account a VAT mapping: that's how the app finds revenue by VAT box and the VAT accounts.":"الرصيد الافتتاحي مع صافي الحركة لكل شهر. المدين بالموجب والدائن بالسالب. حدد تصنيفاً ضريبياً لكل حساب، فبه يحدد التطبيق الإيرادات حسب خانات الإقرار وحسابات الضريبة.","Balance check":"فحص التوازن","Opening":"افتتاحي","Must be zero":"يجب أن يساوي صفراً",
"VAT returns as filed":"الإقرارات الضريبية كما قُدمت","Copy each return exactly as it appears on the ZATCA portal. Enter credit-note adjustments as negative amounts. The app recalculates each return and checks it.":"انقل كل إقرار كما يظهر في بوابة الهيئة تماماً. أدخل تعديلات الإشعارات الدائنة بالسالب. يعيد التطبيق احتساب كل إقرار ويفحصه.","Date filed":"تاريخ التقديم","Return ref":"مرجع الإقرار","Sales":"المبيعات","Purchases":"المشتريات","Amount (SAR)":"المبلغ (ريال)","Adjustment":"التعديل","VAT amount":"مبلغ الضريبة","Borne by the State":"تتحملها الدولة","Total sales":"إجمالي المبيعات","Total purchases":"إجمالي المشتريات","Total VAT due for the period":"إجمالي الضريبة المستحقة للفترة","Corrections from previous periods (max ±5,000)":"تصحيحات من فترات سابقة (بحد أقصى ±5,000)","VAT credit carried forward from previous periods":"الرصيد الدائن المرحّل من فترات سابقة","Net VAT due (or claimed)":"صافي الضريبة المستحقة (أو المطالب باستردادها)","as filed":"كما قُدم",
"VAT on reverse-charge imports (Box 9) counts as both output and input VAT on the return, so it is added to total output VAT here. Check this against your filed return.":"ضريبة الاستيراد بآلية الاحتساب العكسي (خانة 9) تُحتسب كضريبة مخرجات ومدخلات معاً في الإقرار، لذا تُضاف هنا إلى إجمالي ضريبة المخرجات. تحقق من ذلك مقابل الإقرار المقدم.","All periods":"جميع الفترات","over limit":"تجاوز الحد","✗ differs":"✗ مختلف",
"Filed":"تاريخ التقديم","Box 16 recalculated":"خانة 16 بعد إعادة الاحتساب","Box 16 filed":"خانة 16 كما قُدمت","Arithmetic":"الصحة الحسابية","On time":"في الموعد","✓ Agrees":"✓ مطابق","✗ Filed ≠ recalculated":"✗ المقدم ≠ المعاد احتسابه","Not entered":"لم يُدخل","✓ On time":"✓ في الموعد","✗ Over 5,000: voluntary disclosure":"✗ يتجاوز 5,000: إفصاح طوعي","Year":"السنة","Box 16 as filed":"خانة 16 كما قُدمت",
"Every invoice, simplified invoice, credit and debit note. For high-volume point-of-sale, use one summary line per day and VAT category. Credit notes are negative.":"كل فاتورة ضريبية ومبسطة وإشعار دائن ومدين. لمبيعات نقاط البيع الكبيرة استخدم سطراً ملخصاً لكل يوم ولكل فئة ضريبية. الإشعارات الدائنة بالسالب.",
"Every supplier invoice and customs declaration with VAT. The app tests whether the input VAT you claimed would survive an inspection.":"كل فاتورة مورد وبيان جمركي يتضمن ضريبة. يختبر التطبيق ما إذا كانت ضريبة المدخلات المخصومة ستصمد أمام الفحص.",
"One row per SADAD payment. Enter refunds received as negative amounts. Use period 0 for payments of periods before this year.":"صف لكل عملية سداد. أدخل المبالغ المستردة بالسالب. استخدم الفترة 0 لمدفوعات فترات ما قبل هذه السنة.",
"For each box: what you declared, what you invoiced, and what you booked in the ledger. ZATCA usually starts here.":"لكل خانة: ما أقررت به، وما أصدرت به فواتير، وما سجلته في الدفاتر. عادةً تبدأ الهيئة من هنا.","VAT return":"الإقرار الضريبي","Return − register":"الإقرار − السجل","Return − TB":"الإقرار − الميزان","Status":"الحالة","✓ Matched":"✓ مطابق","✗ Investigate":"✗ يحتاج إلى فحص","No activity":"لا يوجد نشاط",
"Revenue in the financial statements against total sales declared for the year. ZATCA treats any unexplained excess as undeclared taxable sales.":"الإيرادات في القوائم المالية مقابل إجمالي المبيعات المُقر بها للسنة. تعتبر الهيئة أي زيادة غير مفسرة مبيعات خاضعة غير مُقر بها.","Total revenue per trial balance (FS class = Revenue)":"إجمالي الإيرادات حسب ميزان المراجعة (التصنيف = إيرادات)","Less: revenue mapped as out of scope / other income":"يُخصم: إيرادات مصنفة خارج النطاق / إيرادات أخرى","Revenue subject to VAT reporting":"الإيرادات الخاضعة للإقرار الضريبي","Total sales per VAT returns (Box 6, full year)":"إجمالي المبيعات حسب الإقرارات (خانة 6، السنة كاملة)","Difference before reconciling items":"الفرق قبل بنود التسوية","Explained reconciling items":"بنود التسوية المفسَّرة","Enter each item with the sign that reduces the difference.":"أدخل كل بند بالإشارة التي تقلل الفرق.","Description":"الوصف","Add item":"إضافة بند","Delete item":"حذف البند","Unexplained difference":"الفرق غير المفسَّر","Explain or correct before submitting":"فسّره أو صحّحه قبل التقديم","Fully reconciled":"مطابق بالكامل",
"Output VAT declared against invoices, the ledger and a 15% recomputation. Box 2 VAT is borne by the State and is left out of the recomputation.":"ضريبة المخرجات المُقر بها مقابل الفواتير والدفاتر وإعادة الاحتساب بنسبة 15%. ضريبة خانة 2 تتحملها الدولة ولا تدخل في إعادة الاحتساب.","Return (incl. RCM)":"الإقرار (شامل الاحتساب العكسي)","Register sales VAT":"ضريبة المبيعات في السجل","Register RCM VAT":"ضريبة الاحتساب العكسي في السجل","15% × (Box 1 + Box 9)":"15% × (خانة 1 + خانة 9)","GL output VAT":"ضريبة المخرجات في الدفاتر","Return − 15%":"الإقرار − 15%","Return − GL":"الإقرار − الدفاتر","Possible under-declaration":"نقص محتمل في الإقرار",
"Input VAT claimed against the register and the ledger, and the part ZATCA is likely to disallow (no valid invoice, blocked expense, invalid supplier VAT number).":"ضريبة المدخلات المخصومة مقابل السجل والدفاتر، والجزء المرجّح أن ترفضه الهيئة (لا توجد فاتورة صحيحة، مصروف غير قابل للخصم، رقم ضريبي غير صحيح للمورد).","Return (Box 12)":"الإقرار (خانة 12)","Register claimed":"المخصوم حسب السجل","Defensible":"القابل للدفاع عنه","At risk":"المعرّض للرفض","GL input VAT":"ضريبة المدخلات في الدفاتر","Possible over-claim":"زيادة محتملة في الخصم","Imports: Box 8 and Box 9":"الاستيراد: خانة 8 وخانة 9","Box 8 VAT (return)":"ضريبة خانة 8 (الإقرار)","Customs VAT (register)":"ضريبة الجمارك (السجل)","Difference":"الفرق","Box 9 VAT (return)":"ضريبة خانة 9 (الإقرار)","RCM VAT (register)":"ضريبة الاحتساب العكسي (السجل)",
"Also match Box 8 to ZATCA's customs import data. Customs VAT is deductible only when your company is the importer of record on the Bayan.":"طابق أيضاً خانة 8 مع بيانات الاستيراد الجمركية لدى الهيئة. ضريبة الجمارك قابلة للخصم فقط إذا كانت منشأتك هي المستورد المسجل في البيان الجمركي.",
"Opening VAT liability per ledger:":"التزام الضريبة الافتتاحي حسب الدفاتر:","Net VAT (Box 13 + 14)":"صافي الضريبة (خانة 13 + 14)","Paid / (refunded)":"المسدد / (المسترد)","Outstanding":"المتبقي","Due":"الاستحقاق","Penalty: paid late":"غرامة: سداد متأخر","Penalty: still unpaid":"غرامة: غير مسدد","GL liability":"الالتزام في الدفاتر","Expected liability":"الالتزام المتوقع",
"Expected liability = opening liability + cumulative (Box 13 + Box 14) − payments dated on or before period end. Late filing (5% to 25% of the tax) and incorrect return (50% of the difference) penalties may also apply.":"الالتزام المتوقع = الالتزام الافتتاحي + المجموع التراكمي (خانة 13 + خانة 14) − المدفوعات حتى نهاية الفترة. قد تنطبق أيضاً غرامة التأخر في التقديم (5% إلى 25% من الضريبة) وغرامة الإقرار الخاطئ (50% من الفرق).",
"Your company":"منشأتك","VAT no":"الرقم الضريبي","valid format":"صيغة صحيحة","check VAT no":"تحقق من الرقم الضريبي","Total indicative exposure":"إجمالي التعرض التقديري","Tax + 50% penalty + late payment":"الضريبة + غرامة 50% + التأخر في السداد","Under-declared output VAT":"ضريبة مخرجات غير مُقر بها","Over-claimed input VAT":"ضريبة مدخلات مخصومة بالزيادة","Unexplained revenue difference":"فرق إيرادات غير مفسَّر","Documents ready":"المستندات الجاهزة","Reconciliation status by period":"حالة المطابقة حسب الفترة","Check":"الفحص","VAT account (GL vs returns − payments)":"حساب الضريبة (الدفاتر مقابل الإقرارات − المدفوعات)","Return arithmetic":"الصحة الحسابية للإقرار","Filed on time":"التقديم في الموعد","What to fix before ZATCA sees it":"ما يجب معالجته قبل أن تراه الهيئة","Open":"فتح","No open issues in the data entered so far.":"لا توجد ملاحظات مفتوحة في البيانات المدخلة حتى الآن.","Exposure breakdown":"تفاصيل التعرض","Tax exposure":"التعرض الضريبي","Late payment penalties (paid late + still unpaid)":"غرامات التأخر في السداد (المسدد متأخراً + غير المسدد)","Total indicative exposure (SAR)":"إجمالي التعرض التقديري (ريال)","Estimates only, before any objection, voluntary disclosure relief or penalty waiver. Confirm with your tax advisor.":"تقديرات فقط، قبل أي اعتراض أو تخفيف عبر الإفصاح الطوعي أو إعفاء من الغرامات. تأكد مع مستشارك الضريبي.",
"What ZATCA usually asks for in a VAT inspection. Track who owns each item and where the file is.":"ما تطلبه الهيئة عادةً في فحص ضريبة القيمة المضافة. تابع المسؤول عن كل بند ومكان ملفه.","Readiness":"الجاهزية","Area":"المجال","Document or analysis":"المستند أو التحليل","Prepared in this app":"مُعدّ في هذا التطبيق","Owner":"المسؤول","File reference":"مرجع الملف",
"General":"عام","Financial":"مالي","Reconciliation":"مطابقة","Cross-tax":"ضرائب أخرى","E-invoicing":"الفوترة الإلكترونية","Response":"الرد على الهيئة",
"VAT returns, Payments":"الإقرارات الضريبية، المدفوعات","Revenue reconciliation":"مطابقة الإيرادات","Sales reconciliation":"مطابقة المبيعات","Output VAT reconciliation":"مطابقة ضريبة المخرجات","Input VAT reconciliation":"مطابقة ضريبة المدخلات","VAT account reconciliation":"مطابقة حساب الضريبة",
"Timing – invoices booked in a different period":"توقيت – فواتير مسجلة في فترة مختلفة","Revenue accruals not yet invoiced":"إيرادات مستحقة لم تصدر بها فواتير","Advance payments invoiced":"دفعات مقدمة صدرت بها فواتير","Other":"أخرى"};
const CHK_AR=["شهادة التسجيل في ضريبة القيمة المضافة، السجل التجاري، عقد التأسيس","وصف الأنشطة ومصادر الإيرادات مع المعالجة الضريبية لكل منها","قائمة الفروع والأطراف ذات العلاقة وأعضاء المجموعة الضريبية","دليل الحسابات مع التصنيف الضريبي","تفاصيل نظام ERP وحل الفوترة الإلكترونية (فاتورة) والربط وشهادة التشفير","خطاب تفويض الممثل المسؤول عن التعامل مع الهيئة","القوائم المالية المدققة لكل سنة محل الفحص","موازين المراجعة الشهرية (افتتاحي، حركات، ختامي)","تفاصيل دفتر الأستاذ للإيرادات والضريبة والمصروفات الرئيسية","كشوف الحسابات البنكية (تقارن الهيئة المتحصلات بالمبيعات المُقر بها)","نسخ جميع الإقرارات المقدمة وإيصالات السداد","الإفصاحات الطوعية والتصحيحات المقدمة (استخدام خانة 14)","مطابقة الإيرادات في القوائم المالية مع إجمالي المبيعات في الإقرارات","مطابقة المبيعات لكل خانة مع سجل المبيعات ودفتر الأستاذ لكل فترة","مطابقة ضريبة المخرجات في الدفاتر مع الإقرارات","مطابقة ضريبة المدخلات في الدفاتر مع الإقرارات","حركة حساب الضريبة المستحقة","مطابقة بيانات الاستيراد الجمركية (البيان) مع خانة 8","سجل المبيعات على مستوى الفاتورة مع الأرقام الضريبية للعملاء","عينات من الفواتير الضريبية والمبسطة والإشعارات الدائنة والمدينة (XML / رمز QR)","إثباتات التصدير: بيانات الخروج الجمركية، بوالص الشحن، العقود، إثبات التحصيل","إثباتات التوريدات المحلية بنسبة صفر (الأدوية المؤهلة، النقل الدولي، وغيرها)","مستندات التوريدات المعفاة (هامش الخدمات المالية، الإيجارات السكنية)","العقود الرئيسية مع العملاء بما فيها العقود الحكومية وبنود الضريبة","التوريدات الافتراضية: العينات المجانية، الهدايا، الاستخدام الخاص، منافع الموظفين، الشطب","تعاملات الأطراف ذات العلاقة والمعالجة الضريبية لها","استبعاد الأصول الثابتة والعقارات (معالجة ضريبة القيمة المضافة / ضريبة التصرفات العقارية)","سجل المشتريات على مستوى الفاتورة مع الأرقام الضريبية للموردين","عينات من فواتير الموردين المؤيدة لضريبة المدخلات المخصومة","البيانات الجمركية للاستيراد وإثبات سداد الضريبة في الجمارك","الاحتساب العكسي: فواتير الموردين الأجانب والعقود وطريقة الاحتساب","تحليل ضريبة المدخلات غير القابلة للخصم (الترفيه، السيارات، منافع الموظفين)","سجل الأصول الثابتة وتعديلات الأصول الرأسمالية","احتساب نسبة توزيع ضريبة المدخلات (في حال وجود توريدات معفاة)","إقرارات ضريبة الاستقطاع (يجب أن تطابق المدفوعات للخارج خانة 9)","مطابقة إيرادات إقرار الزكاة / ضريبة الدخل مع إيرادات ضريبة القيمة المضافة","موجة الربط في المرحلة الثانية وتقرير الفواتير المعتمدة / المبلّغة","تفسير مكتوب لكل فرق يتم اكتشافه"];
const MONRE="(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)";
const mAr=m=>MON_AR[MON.indexOf(m)];
const dAr=s=>s.replace(new RegExp("(\\d{1,2}) "+MONRE+" (\\d{4})","g"),(_,d,m,y)=>`${d} ${mAr(m)} ${y}`);
const PAT=[
 [new RegExp("^"+MONRE+"$"),m=>mAr(m[1])],
 [new RegExp("^"+MONRE+" (\\d{2,4})$"),m=>`${mAr(m[1])} ${m[2]}`],
 [new RegExp("^\\d{1,2} "+MONRE+" \\d{4}$"),m=>dAr(m[0])],
 [/^Q(\d)( \d{4})?$/,m=>`الربع ${m[1]}${m[2]||""}`],
 [/^Box (\d+)$/,m=>`خانة ${m[1]}`],
 [/^Box (\d+) · (.+)$/,m=>`خانة ${m[1]} · ${trx(m[2])}`],
 [/^Sales – Box (\d)$/,m=>`المبيعات – خانة ${m[1]}`],
 [/^Pasted (\d+) rows?$/,m=>`تم لصق ${m[1]} صف`],
 [/^Imported ([\d,]+) rows$/,m=>`تم استيراد ${m[1]} صف`],
 [/^([\d,]+) rows(?: · ([\d,]+) with exceptions)?$/,m=>`${m[1]} صف`+(m[2]?` · ${m[2]} بها ملاحظات`:"")],
 [/^Page (\d+) of (\d+)$/,m=>`صفحة ${m[1]} من ${m[2]}`],
 [/^Delete row (\d+)$/,m=>`حذف الصف ${m[1]}`],
 [/^✗ (\d+) ?d(?:ays)? late$/,m=>`✗ متأخر ${m[1]} يوم`],
 [/^Due (.+)$/,m=>`الاستحقاق ${dAr(m[1])}`],
 [/^Recalculated: (.*)$/,m=>`بعد إعادة الاحتساب: ${m[1]}`],
 [/^(\d+) of (\d+) items$/,m=>`${m[1]} من ${m[2]} بند`],
 [/^(\d+)% ready$/,m=>`جاهز بنسبة ${m[1]}%`],
 [/^SAR (.+)$/,m=>`${m[1]} ريال`],
 [/^· (.+) to (.+) · (Monthly|Quarterly) filing$/,m=>`· من ${dAr(m[1])} إلى ${dAr(m[2])} · إقرار ${m[3]==="Monthly"?"شهري":"ربع سنوي"}`],
 [/^Proves the ledger VAT liability equals returns filed less payments made, and estimates late-payment penalties up to (.+)\.$/,m=>`يثبت أن التزام الضريبة في الدفاتر يساوي الإقرارات المقدمة ناقص المدفوعات، ويقدّر غرامات التأخر في السداد حتى ${dAr(m[1])}.`],
 [/^✓ agrees within SAR (.+) · ✗ needs investigation · · no activity in that period\. Click a row to open the reconciliation\.$/,m=>`✓ مطابق ضمن ${m[1]} ريال · ✗ يحتاج إلى فحص · · لا يوجد نشاط في الفترة. اضغط على أي صف لفتح المطابقة.`],
 [/^Unexplained revenue × (\d+)%$/,m=>`الإيرادات غير المفسرة × ${m[1]}%`],
 [/^Incorrect-return penalty \((\d+)% of the difference\)$/,m=>`غرامة الإقرار الخاطئ (${m[1]}% من الفرق)`],
 [/^Revenue difference of SAR (.+) between the trial balance and the VAT returns is not explained$/,m=>`فرق إيرادات بمبلغ ${m[1]} ريال بين ميزان المراجعة والإقرارات غير مفسَّر`],
 [/^(.+): (\d+) periods? needs? investigation$/,m=>`${trx(m[1])}: ${m[2]} فترة تحتاج إلى فحص`],
 [/^([\d,]+) sales invoices? (?:have|has) exceptions$/,m=>`${m[1]} فاتورة مبيعات بها ملاحظات`],
 [/^([\d,]+) purchase invoices? (?:have|has) exceptions$/,m=>`${m[1]} فاتورة مشتريات بها ملاحظات`],
 [/^Trial balance doesn't balance in (\d+) columns?$/,m=>`ميزان المراجعة غير متوازن في ${m[1]} عمود`],
 [/^(\d+) TB accounts? (?:have|has) no VAT mapping$/,m=>`${m[1]} حساب في الميزان بدون تصنيف ضريبي`],
 [/^SAR (.+) of VAT is still unpaid$/,m=>`${m[1]} ريال من الضريبة لم تُسدد بعد`]];
function trCore(c){if(AR[c]!=null)return AR[c];for(const[re,f]of PAT){const m=re.exec(c);if(m)return f(m)}if(c.includes("; ")){const t=c.split("; ").map(p=>AR[p]);if(t.every(x=>x!=null))return t.join("؛ ")}return null}
function trx(s){const r=trCore(s);return r==null?s:r}
function tr(s){if(LANG!=="ar"||s==null)return s;const m=/^(\s*)([\s\S]*?)(\s*)$/.exec(String(s));if(!m[2])return s;const o=trCore(m[2]);return o==null?s:m[1]+o+m[3]}
function translateNode(root){
  if(LANG!=="ar"||!root)return;
  if(root.nodeType===3){const p=root.parentElement;if(!p||p.closest("script,style,textarea,[data-notr]"))return;const v=tr(root.nodeValue);if(v!==root.nodeValue)root.nodeValue=v;return}
  if(root.nodeType!==1)return;
  if(root.closest&&root.closest("script,style,textarea,[data-notr]"))return;
  const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const list=[];let n;while((n=w.nextNode()))list.push(n);list.forEach(translateNode);
  [root,...root.querySelectorAll("[title],[aria-label],[placeholder]")].forEach(el=>{if(!el.getAttribute)return;for(const a of["title","aria-label","placeholder"]){const v=el.getAttribute(a);if(v){const t=tr(v);if(t!==v)el.setAttribute(a,t)}}});
}
const langObserver=new MutationObserver(ms=>{if(LANG!=="ar")return;for(const m of ms){if(m.type==="characterData")translateNode(m.target);else m.addedNodes.forEach(translateNode)}});
