// ================================================================ test library
R.tests=C=>{const f=UI.tests.f, T=C.tests, cnt=s=>T.filter(t=>t.status===s).length;
  const list=T.filter(t=>f==="all"||(f==="fail"?t.status==="fail":t.area===f));
  const chip=(k,lab,n)=>`<button class="chip" data-tf="${k}" aria-pressed="${f===k}">${esc(lab)}${n!=null?` <span class="cnt">${n}</span>`:""}</button>`;
  const bf=(b,name)=>b&&b.n?`<div class="bf"><div class="row"><b>${esc(name)}</b><span class="note">${esc(L(`${b.n} amounts · MAD ${b.mad.toFixed(4)}`,`${b.n} مبلغ · متوسط الانحراف ${b.mad.toFixed(4)}`))}</span>${pill(b.level==="na"?"none":b.level==="nonconforming"?"bad":b.level==="marginal"?"warn":"ok",{na:L("Too few amounts (need 50+)","عدد المبالغ قليل (يلزم 50 فأكثر)"),close:L("Close conformity","مطابقة قوية"),acceptable:L("Acceptable conformity","مطابقة مقبولة"),marginal:L("Marginal","حدّية"),nonconforming:L("Nonconformity","عدم مطابقة")}[b.level])}</div>${columnChart(["1","2","3","4","5","6","7","8","9"],[{name:L("Actual share","النسبة الفعلية"),c:"s1",values:b.obs.slice(1)},{name:L("Benford expected","المتوقع حسب بنفورد"),c:"s2",type:"line",values:BENFORD.slice(1)}],{h:200,pct:true})}</div>`:"";
  return `<p class="lead">${esc(L(`${T.length} automated tests run on 100% of your data, modelled on the checks used by the Big Four VAT analytics tools and on ZATCA's own risk indicators.`,`${T.length} اختباراً آلياً تُطبق على 100% من بياناتك، مبنية على فحوصات أدوات تحليل الضريبة لدى الشركات الأربع الكبرى ومؤشرات المخاطر لدى الهيئة.`))}</p>
  <div class="tiles four">${tile(L("Tests run","الاختبارات المطبقة"),T.length)}${tile(L("Passed","ناجحة"),cnt("pass"),"","okv")}${tile(L("Failed","فاشلة"),cnt("fail"),"","badv")}${tile(L("Not applicable (no data)","غير منطبقة (لا توجد بيانات)"),cnt("na"))}</div>
  <div class="chips">${chip("fail",L("Failed","فاشلة"),cnt("fail"))}${chip("all",L("All","الكل"),T.length)}${Object.entries(AREAS).map(([k,v])=>chip(k,v,T.filter(t=>t.area===k).length)).join("")}</div>
  <div class="tests">${list.map(t=>{const open=!!UI.tests.open[t.id];return `<article class="test ${t.status}" id="t-${t.id}"><button class="test-h" data-to="${t.id}" aria-expanded="${open}"><span class="st ${t.status}">${icon(STI[t.status])}</span><span class="mono tid">${t.id}</span><span class="tt">${esc(t.title)}</span>${sevPill(t.sev)}<span class="area">${esc(AREAS[t.area])}</span><span class="grow"></span><span class="tm num">${t.status==="na"?esc(L("No data","لا توجد بيانات")):t.status==="pass"?esc(L("Passed","ناجح")):esc(L(`${t.count} items`,`${t.count} بند`))}</span><span class="tm num">${t.tax?fmt(t.tax):""}</span></button>
   ${open?`<div class="test-b"><p class="note"><span>${esc(L("Reference","المرجع"))}</span>: <span>${esc(t.ref)}</span></p>${t.id==="A01"?bf(C.bfS,L("Sales amounts","مبالغ المبيعات")):""}${t.id==="A02"?bf(C.bfP,L("Purchase amounts","مبالغ المشتريات")):""}
    ${t.hits.length?`<div class="frame"><table class="tbl" id="tt-${t.id}"><thead><tr><th>${esc(L("Reference","المرجع"))}</th><th>${esc(L("Date","التاريخ"))}</th><th>${esc(L("Party","الطرف"))}</th><th class="n">${esc(L("Amount","المبلغ"))}</th><th class="n">${esc(L("Tax at risk","الضريبة المعرضة"))}</th></tr></thead><tbody>${t.hits.slice(0,300).map(h=>`<tr><td class="mono">${esc(h.ref)}</td><td>${esc(showDate(h.date))}</td><td data-notr>${esc(h.party)}</td>${nc(h.amount)}${nc(h.tax)}</tr>`).join("")}</tbody></table></div>${t.hits.length>300?`<p class="note">${esc(L(`Showing 300 of ${t.hits.length}.`,`عرض 300 من ${t.hits.length}.`))}</p>`:""}<div class="row"><button class="btn sm" data-copy="tt-${t.id}">${esc("Copy table")}</button><button class="btn sm ghost" data-go="${t.go}">${esc(L("Open the data","فتح البيانات"))}</button></div>`:`<p class="empty">${icon("check")}${esc(t.status==="na"?L("Not enough data to run this test.","لا توجد بيانات كافية لتطبيق هذا الاختبار."):L("No exceptions found.","لا توجد استثناءات."))}</p>`}</div>`:""}</article>`}).join("")||`<p class="empty">${icon("check")}${esc(L("No failed tests.","لا توجد اختبارات فاشلة."))}</p>`}</div>`};
AFTER.tests=()=>{document.querySelectorAll("[data-tf]").forEach(b=>b.onclick=()=>{UI.tests.f=b.dataset.tf;render()});document.querySelectorAll("[data-to]").forEach(b=>b.onclick=()=>{UI.tests.open[b.dataset.to]=!UI.tests.open[b.dataset.to];render();document.getElementById("t-"+b.dataset.to)?.scrollIntoView({block:"nearest"})})};

// ================================================================ findings & exposure
const DEC_AR={"":"—","Correct and disclose":"تصحيح وإفصاح طوعي","Defend with evidence":"الدفاع بالمستندات","Accept assessment":"قبول التقييم","Not an issue":"ليست ملاحظة"};
R.find=C=>{const E=C.exposure, fails=C.tests.filter(t=>t.status==="fail");
  const row=(lab,a,b,cls="")=>`<tr class="${cls}"><td>${esc(lab)}</td>${nc(a)}${nc(b)}</tr>`;
  return `<div class="callout ${E.active?"ok":""}">${icon(E.active?"check":"alert")}<div><b>${esc(L("ZATCA fines cancellation initiative","مبادرة إلغاء الغرامات والإعفاء من العقوبات المالية"))}</b><p>${esc(E.active?L(`Active until ${showDate(C.c.initEnd)} (${E.daysLeft} days left). It covers late registration, late filing, late payment and VAT return correction penalties for returns due on or before ${showDate(C.c.initCut)}, if all returns are filed and the principal tax is paid. It does not cover evasion penalties.`,`سارية حتى ${dAr(showDate(C.c.initEnd))} (متبقي ${E.daysLeft} يوم). تشمل غرامات التأخر في التسجيل والتقديم والسداد وتصحيح الإقرارات للإقرارات المستحقة حتى ${dAr(showDate(C.c.initCut))}، بشرط تقديم جميع الإقرارات وسداد أصل الضريبة. لا تشمل غرامات التهرب.`):L("Not active under your settings. Check ZATCA's announcements for the current position.","غير سارية حسب إعداداتك. راجع إعلانات الهيئة للوضع الحالي."))}</p></div></div>
  <div class="grid2">${card(L("Exposure by scenario (SAR)","التعرض حسب السيناريو (ريال)"),`<div class="frame"><table class="tbl" id="t-exp"><thead><tr><th></th><th class="n">${esc(L("A: no action","أ: دون إجراء"))}</th><th class="n">${esc(L("B: correct under the initiative","ب: التصحيح ضمن المبادرة"))}</th></tr></thead><tbody>
   ${row(L("Under-declared output VAT","ضريبة مخرجات غير مُقر بها"),E.out,E.out)}${row(L("Over-claimed input VAT","ضريبة مدخلات مخصومة بالزيادة"),E.inp,E.inp)}${row(L("Tax to pay","الضريبة المستحقة"),E.tax,E.tax,"total")}
   ${row(L("Incorrect-return penalty (50%)","غرامة الإقرار الخاطئ (50%)"),E.pen,E.pen-E.rows.filter(r=>r.eligible).reduce((s,r)=>s+r.pen,0)*(E.active?1:0))}${row(L("Late payment penalties","غرامات التأخر في السداد"),E.latePay,E.latePay-E.rows.filter(r=>r.eligible).reduce((s,r)=>s+r.latePay,0)*(E.active?1:0))}${row(L("Late filing penalty (minimum 5%)","غرامة التأخر في التقديم (5% كحد أدنى)"),E.lateFile,E.lateFile-E.rows.filter(r=>r.eligible).reduce((s,r)=>s+r.lateFile,0)*(E.active?1:0))}
   ${row(L("Total","الإجمالي"),E.A,E.B,"total")}</tbody></table></div><p class="note">${esc(L("Output exposure takes the higher of under-declared VAT and unexplained revenue × rate, so one error is never counted twice. Late filing can reach 25%; 5% is shown.","يؤخذ تعرض المخرجات بالأعلى بين الضريبة غير المُقر بها والإيرادات غير المفسرة × النسبة، فلا يُحتسب الخطأ مرتين. قد تصل غرامة التأخر في التقديم إلى 25%، والمعروض 5%."))}</p><div class="row"><button class="btn sm" data-copy="t-exp">${esc("Copy table")}</button></div>`)}
   ${card(L("Exposure by period (SAR)","التعرض حسب الفترة (ريال)"),(()=>{const rs=E.rows.filter(r=>r.tax||r.allPen);return rs.length?`<div class="frame"><table class="tbl"><thead><tr><th>${esc("Period")}</th><th class="n">${esc(L("Tax","الضريبة"))}</th><th class="n">${esc(L("Penalties","الغرامات"))}</th><th>${esc(L("Initiative","المبادرة"))}</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.tax)}${nc(r.allPen)}<td>${r.eligible&&E.active?pill("ok",L("Eligible","مؤهلة")):pill("none",L("Not eligible","غير مؤهلة"))}</td></tr>`).join("")}</tbody></table></div>`:`<p class="empty">${icon("check")}${esc(L("No exposure in any period.","لا يوجد تعرض في أي فترة."))}</p>`})())}</div>
  ${card(L("Findings register","سجل الملاحظات"),fails.length?`<div class="frame"><table class="tbl edit" id="t-find"><thead><tr><th>ID</th><th>${esc(L("Finding","الملاحظة"))}</th><th>${esc(L("Severity","الخطورة"))}</th><th class="n">${esc(L("Items","البنود"))}</th><th class="n">${esc(L("Tax at risk","الضريبة المعرضة"))}</th><th>${esc(L("Decision","القرار"))}</th><th>${esc(L("Explanation for ZATCA","التفسير للهيئة"))}</th></tr></thead><tbody>
   ${fails.map(t=>{const d=S.decisions[t.id]||{};return `<tr><td class="mono"><button class="link" data-test="${t.id}">${t.id}</button></td><td style="min-width:220px">${esc(t.title)}</td><td>${sevPill(t.sev)}</td><td class="n">${t.count}</td>${nc(t.tax)}<td><select data-dec="${t.id}" data-f="d">${DECISIONS.map(o=>`<option value="${o}"${o===(d.d||"")?" selected":""}>${esc(LANG==="ar"?DEC_AR[o]:(o||"—"))}</option>`).join("")}</select></td><td><input data-dec="${t.id}" data-f="n" value="${esc(d.n||"")}" style="min-width:240px" placeholder="${esc(L("Why, and what evidence supports it","السبب، وما المستندات المؤيدة"))}"></td></tr>`}).join("")}</tbody></table></div>
   <div class="row"><button class="btn sm" data-copy="t-find">${esc("Copy table")}</button><span class="note">${esc(L(`${fails.filter(t=>(S.decisions[t.id]||{}).d).length} of ${fails.length} findings have a decision.`,`${fails.filter(t=>(S.decisions[t.id]||{}).d).length} من ${fails.length} ملاحظة لها قرار.`))}</span></div>`:`<p class="empty">${icon("check")}${esc(L("No findings.","لا توجد ملاحظات."))}</p>`)}`};
AFTER.find=()=>{document.querySelectorAll("[data-dec]").forEach(el=>{const h=()=>{const k=el.dataset.dec;S.decisions[k]=S.decisions[k]||{d:"",n:""};S.decisions[k][el.dataset.f]=el.value;save()};el.addEventListener("input",h);el.addEventListener("change",h)});AFTER.dash()};

// ================================================================ sampling
R.samp=C=>{const sm=sampleItems(C), s=S.sample, it=sm.items;const vs=it.map(o=>S.vouch[o.key]||{s:"Not tested",n:""});
  const tested=vs.filter(v=>v.s&&v.s!=="Not tested").length, exc=vs.filter(v=>v.s==="Exception").length;
  return `<p class="lead">${esc(L("Monetary-unit sampling: larger invoices are more likely to be picked. Use it to vouch invoices to source documents before ZATCA does. The same seed always gives the same sample.","العينة بالوحدة النقدية: الفواتير الأكبر أكثر احتمالاً للاختيار. استخدمها لمطابقة الفواتير مع مستنداتها قبل الهيئة. نفس الرقم الأولي يعطي نفس العينة دائماً."))}</p>
  ${card("",`<div class="form-grid four"><label class="fld"><span>${esc(L("Population","المجتمع"))}</span><select id="s-pop"><option value="sales"${s.pop!=="purchases"?" selected":""}>${esc("Sales register")}</option><option value="purchases"${s.pop==="purchases"?" selected":""}>${esc("Purchase register")}</option></select></label><label class="fld"><span>${esc(L("Sample size","حجم العينة"))}</span><input id="s-size" inputmode="numeric" value="${esc(s.size)}"></label><label class="fld"><span>${esc(L("Seed","الرقم الأولي"))}</span><input id="s-seed" value="${esc(s.seed)}"></label></div>`)}
  <div class="tiles four">${tile(L("Population value (SAR)","قيمة المجتمع (ريال)"),`<span class="num">${fmt0(sm.total)}</span>`)}${tile(L("Sampling interval","فترة المعاينة"),`<span class="num">${fmt0(sm.interval)}</span>`)}${tile(L("Tested","تم فحصها"),`${tested} / ${it.length}`)}${tile(L("Exceptions","الاستثناءات"),exc,"",exc?"badv":"")}</div>
  ${card(L("Sample","العينة"),it.length?`<div class="frame"><table class="tbl edit" id="t-samp"><thead><tr><th>#</th><th>${esc(L("Reference","المرجع"))}</th><th>${esc(L("Date","التاريخ"))}</th><th>${esc(L("Party","الطرف"))}</th><th class="n">${esc(L("Net (SAR)","الصافي (ريال)"))}</th><th class="n">${esc(L("VAT (SAR)","الضريبة (ريال)"))}</th><th>${esc(L("Result","النتيجة"))}</th><th>${esc("Notes")}</th></tr></thead><tbody>
   ${it.map((o,k)=>{const v=S.vouch[o.key]||{s:"Not tested",n:""};return `<tr><td class="rowno">${k+1}</td><td class="mono">${esc(o.r.no)}</td><td>${esc(showDate(o.r.date))}</td><td data-notr>${esc(o.r.cust||o.r.sup||"")}</td>${nc(o.x.net)}${nc(o.x.vat)}<td><select data-vk="${esc(o.key)}" data-f="s">${VOUCH.map(x=>`<option value="${x}"${x===v.s?" selected":""}>${esc(L(x,{"Not tested":"لم يُفحص","Agreed":"مطابق","Exception":"استثناء"}[x]))}</option>`).join("")}</select></td><td><input data-vk="${esc(o.key)}" data-f="n" value="${esc(v.n)}" style="min-width:200px"></td></tr>`}).join("")}</tbody></table></div><div class="row"><button class="btn sm" data-copy="t-samp">${esc("Copy table")}</button></div>`:`<p class="empty">${esc(L("No invoices in this register yet.","لا توجد فواتير في هذا السجل بعد."))}</p>`)}`};
AFTER.samp=()=>{[["s-pop","pop"],["s-size","size"],["s-seed","seed"]].forEach(([id,k])=>$("#"+id).addEventListener("change",e=>{S.sample[k]=e.target.value;save();render()}));
  document.querySelectorAll("[data-vk]").forEach(el=>{const h=()=>{const k=el.dataset.vk;S.vouch[k]=S.vouch[k]||{s:"Not tested",n:""};S.vouch[k][el.dataset.f]=el.value;save()};el.addEventListener("input",h);el.addEventListener("change",()=>{h();if(el.dataset.f==="s")render()})})};

// ================================================================ settings
R.setup=C=>{const s=S.setup;const f=(id,lab,inp,hint)=>`<label class="fld"><span>${esc(lab)}</span>${inp}${hint?`<small>${hint}</small>`:""}</label>`;
  const I=(id,type="text",extra="")=>`<input id="s-${id}" data-s="${id}" type="${type}" value="${esc(s[id])}" ${extra}>`;
  const yn=id=>`<select id="s-${id}" data-s="${id}">${YN.map(o=>`<option value="${o}"${o===s[id]?" selected":""}>${o}</option>`).join("")}</select>`;
  return `${card(L("Company","المنشأة"),`<div class="form-grid">${f("company","Company name",I("company"))}${f("vat","VAT registration number",I("vat","text",'inputmode="numeric" maxlength="15"'),`<span id="vatchk">${vatOk(s.vat)?pill("ok","Valid format"):pill("bad","Invalid format")}</span>`)}${f("cr","Commercial registration no",I("cr"))}</div>`)}
  ${card(L("Year under inspection","السنة محل الفحص"),`<div class="form-grid">${f("fy","Start of the year under inspection",I("fy","date"))}${f("freq","Filing frequency",`<select id="s-freq" data-s="freq"><option value="Monthly"${s.freq==="Monthly"?" selected":""}>Monthly</option><option value="Quarterly"${s.freq==="Quarterly"?" selected":""}>Quarterly</option></select>`)}${f("rate","Standard VAT rate (%)",I("rate","text",'inputmode="decimal"'))}${f("tol","Rounding tolerance (SAR)",I("tol","text",'inputmode="decimal"'))}</div>
   <div class="frame"><table class="tbl"><thead><tr><th>#</th><th>${esc("Period")}</th><th>${esc("Start")}</th><th>${esc("End")}</th><th>${esc("Return & payment due")}</th></tr></thead><tbody>${C.ps.map(p=>`<tr><td>${p.no}</td><td>${p.label}</td><td>${showDate(p.st)}</td><td>${showDate(p.en)}</td><td>${showDate(p.due)}</td></tr>`).join("")}</tbody></table></div>`)}
  ${card(L("Penalties and the fines initiative","الغرامات ومبادرة الإعفاء"),`<div class="form-grid">${f("asof","Penalty calculation date",I("asof","date"))}${f("lpp","Late payment penalty (% per month or part)",I("lpp","text",'inputmode="decimal"'))}${f("irp","Incorrect return penalty (% of the difference)",I("irp","text",'inputmode="decimal"'))}${f("init",L("Apply the fines initiative","تطبيق مبادرة الإعفاء من الغرامات"),yn("init"))}${f("initEnd",L("Initiative ends","نهاية المبادرة"),I("initEnd","date"))}${f("initCut",L("Covers returns due on or before","تشمل الإقرارات المستحقة حتى"),I("initCut","date"))}</div><p class="note">${esc(L("Defaults reflect ZATCA's extension to 31 December 2026 for returns due by 30 June 2026. Check ZATCA's announcements before relying on them.","القيم الافتراضية تعكس تمديد الهيئة حتى 31 ديسمبر 2026 للإقرارات المستحقة حتى 30 يونيو 2026. راجع إعلانات الهيئة قبل الاعتماد عليها."))}</p>`)}`};
AFTER.setup=()=>{document.querySelectorAll("[data-s]").forEach(el=>{el.addEventListener("change",()=>{S.setup[el.dataset.s]=el.value;save();render()});el.addEventListener("input",()=>{S.setup[el.dataset.s]=el.value;save();if(el.dataset.s==="vat")$("#vatchk").innerHTML=vatOk(el.value)?pill("ok","Valid format"):pill("bad","Invalid format")})})};

// ================================================================ response pack (checklist)
R.chk=C=>{const rq=openReq();return `<p class="lead">${esc("What ZATCA usually asks for in a VAT inspection. Track who owns each item and where the file is.")}</p>
 <div class="tiles four">${tile("Readiness",`${Math.round(C.ready*100)}%`,`<div class="meter"><span style="width:${Math.round(C.ready*100)}%"></span></div>`)}${tile(L("Findings with a decision","ملاحظات لها قرار"),`${C.tests.filter(t=>t.status==="fail"&&(S.decisions[t.id]||{}).d).length} / ${C.tests.filter(t=>t.status==="fail").length}`)}${tile(L("ZATCA requests answered","طلبات الهيئة المجابة"),`${rq.filter(r=>r.status==="Submitted"||r.status==="Closed").length} / ${rq.length}`)}${tile(L("Sample items tested","بنود العينة المفحوصة"),`${Object.values(S.vouch).filter(v=>v.s&&v.s!=="Not tested").length}`)}</div>
 ${card(L("Document checklist","قائمة المستندات"),`<div class="frame"><table class="tbl edit" id="t-chk"><thead><tr><th>#</th><th>${esc("Area")}</th><th>${esc("Document or analysis")}</th><th>${esc("Prepared in this app")}</th><th>${esc("Status")}</th><th>${esc("Owner")}</th><th>${esc("File reference")}</th><th>${esc("Notes")}</th></tr></thead><tbody>
 ${CHECKLIST.map((c,i)=>{const x=S.checklist[i];return `<tr><td class="rowno">${i+1}</td><td><b>${esc(c[0])}</b></td><td style="min-width:280px">${esc(c[1])}</td><td class="note">${esc(c[2]||"")}</td><td><select data-ck="${i}" data-f="status">${STATUS.map(s=>`<option value="${s}"${s===x.status?" selected":""}>${s}</option>`).join("")}</select></td><td><input data-ck="${i}" data-f="owner" value="${esc(x.owner)}"></td><td><input data-ck="${i}" data-f="ref" value="${esc(x.ref)}"></td><td><input data-ck="${i}" data-f="notes" value="${esc(x.notes)}"></td></tr>`}).join("")}</tbody></table></div><div class="row"><button class="btn sm" data-copy="t-chk">${esc("Copy table")}</button></div>`)}`};
AFTER.chk=()=>{document.querySelectorAll("[data-ck]").forEach(el=>{const h=()=>{S.checklist[+el.dataset.ck][el.dataset.f]=el.value;save()};el.addEventListener("input",h);el.addEventListener("change",()=>{h();if(el.dataset.f==="status")render()})})};

// ================================================================ methodology
R.method=C=>{const firms=[["KPMG","AVA / Tax Intelligence Solution",L("Tests the whole invoice population, predicts mis-booked invoices with machine learning, then an expert validates every hit.","يختبر جميع الفواتير، ويتنبأ بالفواتير المسجلة خطأً بالتعلم الآلي، ثم يتحقق خبير من كل نتيجة."),L("100% testing + human decision on every finding","اختبار 100% + قرار بشري لكل ملاحظة")],
  ["Deloitte","Global VAT/GST Radar · myInsight",L("Predefined checks and balances on VAT data, one dashboard, and an issue log with management reporting.","فحوصات محددة مسبقاً على بيانات الضريبة، ولوحة واحدة، وسجل ملاحظات مع تقارير للإدارة."),L("Numbered test library + findings register","مكتبة اختبارات مرقمة + سجل ملاحظات")],
  ["EY","Global VAT Reporting Tool",L("Uploads data from many systems, parameter tests, anomaly detection, tax calendar and an audit trail for returns.","رفع البيانات من عدة أنظمة، واختبارات معيارية، وكشف الأنماط غير الطبيعية، وتقويم ضريبي، وسجل تدقيق للإقرارات."),L("Data hub, anomaly analytics, deadlines, audit log","مركز بيانات، وتحليلات الأنماط، والمواعيد، وسجل التدقيق")],
  ["PwC","Indirect Tax Edge · VAT Data Check",L("Controls testing over 100% of transactions with 200+ compliance and data-quality checks.","اختبار الضوابط على 100% من المعاملات بأكثر من 200 فحص للالتزام وجودة البيانات."),L("Data-quality tests separated from tax tests","فصل اختبارات جودة البيانات عن الاختبارات الضريبية")],
  ["BDO","ONESOURCE Fast VAT (KSA/UAE)",L("Automated return preparation and periodic VAT health checks for GCC clients.","إعداد آلي للإقرارات وفحوصات دورية لسلامة الضريبة لعملاء الخليج."),L("Return-level controls and tie-outs","ضوابط على مستوى الإقرار ومطابقاته")],
  ["ZATCA",L("Risk engine and audit process","محرك المخاطر وإجراءات الفحص"),L("Selects cases by analytics (mismatches, frequent amendments, large refunds, e-invoice inconsistencies), then document requests, queries, assessment, objection.","تختار الحالات بالتحليلات (الفروق، التعديلات المتكررة، الاستردادات الكبيرة، تعارضات الفوترة الإلكترونية)، ثم طلب المستندات، والاستفسارات، والتقييم، والاعتراض."),L("Tests mirror ZATCA's risk triggers; case file tracks every request","الاختبارات تحاكي مؤشرات الهيئة؛ وملف الفحص يتابع كل طلب")]];
  return `<p class="lead">${esc(L("How this system was designed: what the leading VAT review tools do, and what was taken from each.","كيف صُمم هذا النظام: ماذا تفعل أفضل أدوات مراجعة الضريبة، وماذا أُخذ من كل منها."))}</p>
  ${card(L("Research","البحث"),`<div class="frame"><table class="tbl"><thead><tr><th>${esc(L("Firm","الجهة"))}</th><th>${esc(L("System","النظام"))}</th><th>${esc(L("What it does","ماذا يفعل"))}</th><th>${esc(L("Built into this system","ما أُدرج في هذا النظام"))}</th></tr></thead><tbody>${firms.map(f=>`<tr><td><b>${f[0]}</b></td><td>${esc(f[1])}</td><td style="min-width:280px">${esc(f[2])}</td><td>${esc(f[3])}</td></tr>`).join("")}</tbody></table></div><p class="note">${esc(L("Based on the firms' public product pages and ZATCA publications. The firms' internal tools are not public; this system reproduces the approach, not their software.","استناداً إلى صفحات المنتجات العامة للشركات ومنشورات الهيئة. الأدوات الداخلية للشركات غير منشورة؛ هذا النظام يحاكي المنهجية وليس برمجياتها."))}</p>`)}
  ${card(L("Workflow","سير العمل"),`<ol class="steps">${[[L("Load","التحميل"),L("Trial balance, returns, registers, payments.","ميزان المراجعة والإقرارات والسجلات والمدفوعات.")],[L("Detect","الاكتشاف"),L(`${TESTS.length} tests on 100% of the data, plus five reconciliations.`,`${TESTS.length} اختباراً على 100% من البيانات، وخمس مطابقات.`)],[L("Quantify","التقدير"),L("Tax and penalties per finding, with and without the fines initiative.","الضريبة والغرامات لكل ملاحظة، مع المبادرة ودونها.")],[L("Decide","القرار"),L("Correct and disclose, defend with evidence, or accept.","التصحيح والإفصاح، أو الدفاع بالمستندات، أو القبول.")],[L("Respond","الرد"),L("Checklist, request log and copy-ready tables for ZATCA.","قائمة المستندات وسجل الطلبات وجداول جاهزة للنسخ.")]].map(([a,b])=>`<li><b>${esc(a)}</b><span>${esc(b)}</span></li>`).join("")}</ol>`)}
  ${card(L("Test catalogue","دليل الاختبارات"),`<div class="frame"><table class="tbl" id="t-cat"><thead><tr><th>ID</th><th>${esc(L("Area","المجال"))}</th><th>${esc(L("Test","الاختبار"))}</th><th>${esc(L("Severity","الخطورة"))}</th><th>${esc(L("Reference","المرجع"))}</th></tr></thead><tbody>${TESTS.map(t=>`<tr><td class="mono">${t.id}</td><td>${esc(AREAS[t.area])}</td><td>${esc(t.title)}</td><td>${sevPill(t.sev)}</td><td class="note">${esc(t.ref)}</td></tr>`).join("")}</tbody></table></div><div class="row"><button class="btn sm" data-copy="t-cat">${esc("Copy table")}</button></div>`)}`};
