// ================================================================ data grids
const COL={
 tb:()=>{const ml=monthLabels();return[{k:"code",h:"Account code",t:"text",w:90},{k:"name",h:"Account name",t:"text",w:200},{k:"fs",h:"FS class",t:"sel",o:FS,w:110},{k:"map",h:"VAT mapping",t:"sel",o:TB_MAPS,w:230},{k:"open",h:"Opening balance",t:"num",w:120},...ml.map((l,m)=>({k:"m"+m,h:l,t:"num",w:110}))]},
 sales:()=>[{k:"date",h:"Invoice date",t:"date"},{k:"no",h:"Invoice no",t:"text"},{k:"type",h:"Document type",t:"sel",o:DOC_TYPES},{k:"cust",h:"Customer",t:"text",w:170},{k:"cvat",h:"Customer VAT no",t:"text",w:150},{k:"ctype",h:"Customer type",t:"sel",o:CUST_TYPES},{k:"cat",h:"VAT category",t:"sel",o:SALES_CATS,w:220},{k:"net",h:"Net (SAR)",t:"num"},{k:"vat",h:"VAT (SAR)",t:"num"},{k:"uuid",h:"E-invoice UUID",t:"text"},{k:"fat",h:"On FATOORA?",t:"sel",o:YN,w:80},{k:"gl",h:"GL account",t:"text",w:80},{k:"ev",h:"Export / zero-rate evidence",t:"text",w:200}],
 pur:()=>[{k:"date",h:"Invoice date",t:"date"},{k:"no",h:"Supplier invoice no",t:"text"},{k:"sup",h:"Supplier",t:"text",w:170},{k:"svat",h:"Supplier VAT no",t:"text",w:150},{k:"country",h:"Country",t:"text"},{k:"cat",h:"VAT category",t:"sel",o:PUR_CATS,w:230},{k:"nature",h:"Expense nature",t:"sel",o:NATURE,w:220},{k:"net",h:"Net (SAR)",t:"num"},{k:"vat",h:"VAT (SAR)",t:"num"},{k:"valid",h:"Valid tax invoice?",t:"sel",o:YN,w:80},{k:"claimed",h:"Claimed in return?",t:"sel",o:YN,w:80},{k:"bayan",h:"Customs decl. (Bayan)",t:"text"},{k:"gl",h:"GL account",t:"text",w:80}],
 pay:()=>[{k:"p",h:"Period # (0 = prior)",t:"num",w:80},{k:"date",h:"Payment date",t:"date"},{k:"ref",h:"SADAD / reference",t:"text"},{k:"amt",h:"Amount (SAR, refunds −)",t:"num"},{k:"notes",h:"Notes",t:"text",w:200}]};
const COMP={
 tb:[{h:"Total movements",n:1,f:r=>r.m.reduce((s,v)=>s+num(v),0)},{h:"Closing balance",n:1,f:r=>num(r.open)+r.m.reduce((s,v)=>s+num(v),0)}],
 sales:[{h:"Period",f:(r,x)=>x?(x.p||"—"):""},{h:"Expected VAT",n:1,f:(r,x)=>x?x.exp:""},{h:"VAT difference",n:1,f:(r,x)=>x?x.diff:""},{h:"Exceptions",flags:1,f:(r,x)=>x?x.flags.join("; "):""}],
 pur:[{h:"Period",f:(r,x)=>x?(x.p||"—"):""},{h:"Expected VAT",n:1,f:(r,x)=>x?x.exp:""},{h:"VAT claimed",n:1,f:(r,x)=>x?x.claimed:""},{h:"Defensible VAT",n:1,f:(r,x)=>x?x.defensible:""},{h:"VAT at risk",n:1,f:(r,x)=>x?x.risk:""},{h:"Exceptions",flags:1,f:(r,x)=>x?x.flags.join("; "):""}],
 pay:[{h:"Period",f:(r,x)=>x.label},{h:"Due date",f:(r,x)=>x.due?showDate(x.due):""},{h:"Days late",n:1,f:(r,x)=>x.days||""},{h:"Months late",n:1,f:(r,x)=>x.ml||""},{h:"Est. penalty",n:1,f:(r,x)=>x.pen}]};
L("Duplicate supplier invoice","فاتورة مورد مكررة");L("Foreign supplier without reverse charge","مورد أجنبي دون احتساب عكسي");
const DATA={tb:()=>S.tb,sales:()=>S.sales,pur:()=>S.purchases,pay:()=>S.payments};
const NEWROW={tb:()=>({code:"",name:"",fs:"",map:"",open:"",m:Array(12).fill("")}),sales:()=>({}),pur:()=>({}),pay:()=>({})};
function getV(key,row,k){if(key==="tb"&&/^m\d+$/.test(k))return row.m[+k.slice(1)]??"";return row[k]??""}
function setV(key,row,k,v){if(key==="tb"&&/^m\d+$/.test(k)){row.m[+k.slice(1)]=v;return}row[k]=v}
function rowCalc(key,i,C){if(key==="sales")return C.sales[i];if(key==="pur")return C.pur[i];if(key==="pay")return C.pays[i];return null}
const PAGE=100;
function gridHTML(key,C){
  const cols=COL[key](), comp=COMP[key], data=DATA[key](), ui=UI[key]||(UI[key]={page:0,flagged:false});
  let idx=data.map((_,i)=>i);if(ui.flagged)idx=idx.filter(i=>{const x=rowCalc(key,i,C);return x&&x.flags&&x.flags.length});
  const pages=Math.max(1,Math.ceil(idx.length/PAGE));if(ui.page>=pages)ui.page=pages-1;const slice=idx.slice(ui.page*PAGE,(ui.page+1)*PAGE);
  const flagBtn=(key==="sales"||key==="pur")?`<button class="btn sm" data-g="flag" aria-pressed="${ui.flagged}">${esc(ui.flagged?"Show all rows":"Show only rows with exceptions")}</button>`:"";
  const tools=`<div class="toolbar"><button class="btn sm primary" data-g="add">${esc("Add row")}</button><button class="btn sm" data-g="import">${icon("upl")}${esc("Import from Excel / CSV")}</button>${flagBtn}<button class="btn sm" data-g="copy">${esc("Copy table")}</button><button class="btn sm danger" data-g="clearall">${esc("Clear this table")}</button><span class="grow"></span><span class="note">${fmtInt(data.length)} rows${ui.flagged?` · ${fmtInt(idx.length)} with exceptions`:""}</span>${pages>1?`<button class="btn sm" data-g="prev" ${ui.page?"":"disabled"}>‹</button><span class="note">Page ${ui.page+1} of ${pages}</span><button class="btn sm" data-g="next" ${ui.page<pages-1?"":"disabled"}>›</button>`:""}</div>
  <p class="note tip-line">${esc("Tip: copy a block of cells from Excel and paste into any cell here. Rows are added automatically. Dates can be dd/mm/yyyy or yyyy-mm-dd.")}</p>`;
  const head=`<tr><th></th>${cols.map(c=>`<th class="${c.t==="num"?"n":""}">${esc(c.h)}</th>`).join("")}${comp.map(c=>`<th class="${c.n?"n":""} calc">${esc(c.h)}</th>`).join("")}<th></th></tr>`;
  const body=slice.map(i=>{const row=data[i],x=rowCalc(key,i,C);return `<tr data-i="${i}"><td class="rowno">${i+1}</td>${cols.map((c,ci)=>`<td>${cellInput(c,getV(key,row,c.k),ci)}</td>`).join("")}${comp.map((c,j)=>compCell(c,row,x,j)).join("")}<td><button class="del" data-g="del" aria-label="Delete row ${i+1}">×</button></td></tr>`}).join("")
    ||`<tr><td colspan="${cols.length+comp.length+2}" class="empty">${esc(ui.flagged?"No rows with exceptions.":"No rows yet. Paste from Excel, import a file, or add a row.")}</td></tr>`;
  return tools+`<div class="frame grid" data-grid="${key}"><table class="tbl edit" id="t-${key}"><thead>${head}</thead><tbody>${body}</tbody></table></div>`;
}
function cellInput(c,v,ci){const st=c.w?` style="min-width:${c.w}px"`:"";
  if(c.t==="sel"){const opts=[...c.o];if(v&&!opts.includes(v))opts.push(v);return `<select data-k="${c.k}" data-ci="${ci}"${st}><option value=""></option>${opts.map(o=>`<option value="${esc(o)}"${o===v?" selected":""}>${esc(o)}</option>`).join("")}</select>`}
  if(c.t==="date")return `<input type="date" data-k="${c.k}" data-ci="${ci}" value="${esc(v)}"${st}>`;
  return `<input type="text" ${c.t==="num"?'inputmode="decimal" class="num"':""} data-k="${c.k}" data-ci="${ci}" value="${esc(v)}"${st}>`}
function compCell(c,row,x,j){const v=c.f(row,x);if(c.flags)return `<td class="calc flags" data-c="${j}">${esc(v)}</td>`;return `<td class="calc ${c.n?"n":""}" data-c="${j}">${c.n&&v!==""?fmt(v):esc(v)}</td>`}
function bindGrid(key){
  const wrap=document.querySelector(`[data-grid="${key}"]`);if(!wrap)return;const tb=wrap.querySelector("tbody"),cols=COL[key](),data=DATA[key];
  const upd=e=>{const el=e.target;if(!el.dataset.k)return;const tr=el.closest("tr"),i=+tr.dataset.i;setV(key,data()[i],el.dataset.k,el.value);S.example=false;save();
    const C=compute(),x=rowCalc(key,i,C);tr.querySelectorAll("[data-c]").forEach(td=>{const c=COMP[key][+td.dataset.c],v=c.f(data()[i],x);td.textContent=c.n&&v!==""?fmt(v):v});renderNav(C);if(key==="tb")refreshTbCheck(C)};
  tb.addEventListener("input",upd);tb.addEventListener("change",upd);
  tb.addEventListener("paste",e=>{const el=e.target;if(!el.dataset||el.dataset.ci==null)return;const txt=(e.clipboardData||window.clipboardData).getData("text");if(!/[\t\n]/.test(txt.replace(/\s+$/,"")))return;e.preventDefault();
    const lines=txt.replace(/\r/g,"").replace(/\n+$/,"").split("\n").map(l=>l.split("\t"));const start=+el.closest("tr").dataset.i,ci=+el.dataset.ci;
    lines.forEach((cells,ri)=>{let row=data()[start+ri];if(!row){row=NEWROW[key]();data().push(row)}cells.forEach((v,k)=>{const c=cols[ci+k];if(c)setV(key,row,c.k,normCell(c,v))})});
    S.example=false;save();render();toast(`Pasted ${lines.length} row${lines.length>1?"s":""}`)});
  tb.addEventListener("click",e=>{const b=e.target.closest('[data-g="del"]');if(!b)return;data().splice(+b.closest("tr").dataset.i,1);save();render()});
  wrap.parentElement.querySelector(".toolbar").addEventListener("click",e=>{const b=e.target.closest("[data-g]");if(!b)return;const ui=UI[key];
    if(b.dataset.g==="add"){data().push(NEWROW[key]());ui.flagged=false;ui.page=Math.floor((data().length-1)/PAGE);save();render();document.querySelector(`[data-grid="${key}"] tbody tr:last-child input`)?.focus()}
    if(b.dataset.g==="flag"){ui.flagged=!ui.flagged;ui.page=0;render()}
    if(b.dataset.g==="prev"){ui.page--;render()}if(b.dataset.g==="next"){ui.page++;render()}
    if(b.dataset.g==="copy")copyText(tableTSV(document.getElementById("t-"+key)));
    if(b.dataset.g==="clearall")confirmBox("Delete every row in this table?","Delete rows",()=>{data().length=0;save();render()});
    if(b.dataset.g==="import")pickFile(wb=>importTable(key,wb))});
}
function normCell(c,v){v=v==null?"":v;if(c.t==="date")return normDate(v);if(c.t==="sel")return normSel(v,c.o);if(c.t==="num"){if(v===""||v==null)return "";return String(num(v))}return String(v).trim()}
function rowsInto(key,rows,colCount){const cols=COL[key]();let n=0;for(const r of rows){if(!r.slice(0,colCount).some(v=>String(v).trim()!==""))continue;const row=NEWROW[key]();cols.forEach((c,k)=>setV(key,row,c.k,normCell(c,r[k])));DATA[key]().push(row);n++}return n}
const SHEET_AR={Setup:"الإعدادات",Checklist:"قائمة_المستندات",TB_Monthly:"ميزان_المراجعة",VAT_Returns:"الإقرارات",Sales_Register:"سجل_المبيعات",Purchase_Register:"سجل_المشتريات",ZATCA_Payments:"المدفوعات"};
function importTable(key,wb){
  const tmpl={tb:"TB_Monthly",sales:"Sales_Register",pur:"Purchase_Register",pay:"ZATCA_Payments"}[key];let rows,ws=wb.Sheets[tmpl]||wb.Sheets[SHEET_AR[tmpl]];
  if(ws){rows=sheetRows(ws).slice(5);if(key==="sales"||key==="pur")rows=rows.map(dropTotal)}
  else{rows=sheetRows(wb.Sheets[wb.SheetNames[0]]);const ni={tb:4,sales:7,pur:7,pay:3}[key];if(rows.length&&typeof rows[0][ni]==="string"&&rows[0][ni]!==""&&!/^[\d,.()\-\s]+$/.test(rows[0][ni]))rows=rows.slice(1)}
  if(key==="tb")rows=rows.filter(r=>String(r[0]).trim()!==""||String(r[1]).trim()!=="");
  const n=rowsInto(key,rows,COL[key]().length);S.example=false;save();render();toast(`Imported ${fmtInt(n)} rows`)}
function importWorkbook(wb){
  const sh=n=>wb.Sheets[n]||wb.Sheets[SHEET_AR[n]],has=n=>!!sh(n);
  if(!has("TB_Monthly")&&!has("Sales_Register")&&!has("VAT_Returns")){toast("This isn't the VAT Inspection Pack workbook. Use the Import button on each table instead.");return}
  const keep={setup:S.setup,case:S.case,requests:S.requests};S=exampleState();Object.assign(S,keep);S.example=false;S.tb=[];S.sales=[];S.purchases=[];S.payments=[];S.decisions={};S.vouch={};S.returns=Array.from({length:12},blankReturn);
  if(has("Setup")){const r=sheetRows(sh("Setup"));const g=i=>(r[i]||[])[1];const pc=v=>{const n=num(v);return String(n<=1?r2(n*100):n)};Object.assign(S.setup,{company:String(g(3)||""),vat:String(g(4)||""),cr:String(g(5)||""),fy:normDate(g(6))||"2025-01-01",freq:(g(7)==="Quarterly"||g(7)==="ربع سنوي")?"Quarterly":"Monthly",rate:pc(g(8)),tol:String(num(g(9))),asof:normDate(g(10))||S.setup.asof,lpp:pc(g(11)),irp:pc(g(12))})}
  if(has("TB_Monthly"))rowsInto("tb",sheetRows(sh("TB_Monthly")).slice(5).filter(r=>String(r[0]).trim()||String(r[1]).trim()),17);
  if(has("Sales_Register"))rowsInto("sales",sheetRows(sh("Sales_Register")).slice(5).map(dropTotal),13);
  if(has("Purchase_Register"))rowsInto("pur",sheetRows(sh("Purchase_Register")).slice(5).map(dropTotal),13);
  if(has("ZATCA_Payments"))rowsInto("pay",sheetRows(sh("ZATCA_Payments")).slice(5),5);
  if(has("VAT_Returns")){const rr=sheetRows(sh("VAT_Returns"));for(let i=0;i<12;i++){const r=rr[5+i]||[],t=S.returns[i];const sv=v=>v===""||v==null?"":String(num(v));t.filed=normDate(r[3]);t.ref=String(r[4]||"");BOX_IDS.forEach((b,k)=>{const c=5+3*k;t.b[b]={a:sv(r[c]),j:sv(r[c+1]),v:sv(r[c+2])}});t.b14=sv(r[35]);t.b15=sv(r[36]);t.b16=sv(r[37])}}
  if(has("Checklist")){const rr=sheetRows(sh("Checklist"));S.checklist.forEach((c,i)=>{const r=rr[4+i]||[];if(r[6])c.status=normSel(r[6],STATUS);c.owner=String(r[4]||"");c.ref=String(r[7]||"");c.notes=String(r[8]||"")})}
  save();render();toast("Workbook imported")}

// ================================================================ data pages
R.tb=C=>`<p class="lead">${esc("Opening balance plus the net movement for each month. Debits positive, credits negative. Give every account a VAT mapping: that's how the app finds revenue by VAT box and the VAT accounts.")}</p>
 ${card("Balance check",`<div class="frame"><table class="tbl"><thead><tr><th></th><th class="n">${esc("Opening")}</th>${monthLabels().map(l=>`<th class="n">${l}</th>`).join("")}</tr></thead><tbody><tr id="tbcheck"></tr></tbody></table></div>`)}${gridHTML("tb",C)}`;
function refreshTbCheck(C){const tr=$("#tbcheck");if(!tr)return;tr.innerHTML=`<td>${esc("Must be zero")}</td>`+C.tbCheck.map(v=>`<td class="n">${Math.abs(v)>0.005?pill("bad",fmt(v)):pill("ok","✓")}</td>`).join("")}
AFTER.tb=C=>{refreshTbCheck(C);bindGrid("tb")};
R.sales=C=>`<p class="lead">${esc("Every invoice, simplified invoice, credit and debit note. For high-volume point-of-sale, use one summary line per day and VAT category. Credit notes are negative.")}</p>`+gridHTML("sales",C);AFTER.sales=()=>bindGrid("sales");
R.pur=C=>`<p class="lead">${esc("Every supplier invoice and customs declaration with VAT. The app tests whether the input VAT you claimed would survive an inspection.")}</p>`+gridHTML("pur",C);AFTER.pur=()=>bindGrid("pur");
R.pay=C=>`<p class="lead">${esc("One row per SADAD payment. Enter refunds received as negative amounts. Use period 0 for payments of periods before this year.")}</p>`+gridHTML("pay",C);AFTER.pay=()=>bindGrid("pay");

// ================================================================ VAT returns form
R.ret=C=>{const ps=C.ps,k=Math.min(UI.ret.p,ps.length-1),p=ps[k],r=S.returns[k];
  const chip=(pp,i)=>{const X=C.rets[i];const st=X.arith==="bad"||X.late==="bad"?"bad":X.entered?"ok":"none";return `<button class="chip" data-rp="${i}" aria-pressed="${i===k}"><i class="dotc ${st}"></i>${esc(pp.label)}</button>`};
  const inp=(b,f)=>`<input class="num" inputmode="decimal" data-b="${b}" data-f="${f}" value="${esc(r.b[b][f])}" aria-label="Box ${b} ${f}">`;
  const boxRow=x=>`<tr><td class="boxno">Box ${x.b}</td><td><div class="boxname"><span>${esc(x.en)}</span><span class="ar">${esc(x.ar)}</span></div></td><td>${inp(x.b,"a")}</td><td>${inp(x.b,"j")}</td><td>${x.b===2?`<small class="note">${esc("Borne by the State")}</small>`:""}${inp(x.b,"v")}</td></tr>`;
  const tot=(no,en,id1,id2)=>`<tr class="total"><td class="boxno">Box ${no}</td><td>${esc(en)}</td><td class="n" colspan="2" id="${id1}"></td><td class="n" id="${id2}"></td></tr>`;
  return `<p class="lead">${esc("Copy each return exactly as it appears on the ZATCA portal. Enter credit-note adjustments as negative amounts. The app recalculates each return and checks it.")}</p>
  <div class="chips">${ps.map(chip).join("")}</div>
  <section class="card form"><div class="toolbar"><b class="h3">${esc(p.label)}</b><span class="note">${esc("Due "+showDate(p.due))}</span><span class="grow"></span><label class="fld inline"><span>${esc("Date filed")}</span><input type="date" data-top="filed" value="${esc(r.filed)}"></label><label class="fld inline"><span>${esc("Return ref")}</span><input data-top="ref" value="${esc(r.ref)}"></label></div>
   <div class="frame"><table class="tbl ret"><thead><tr><th></th><th>${esc("Sales")}</th><th class="n">${esc("Amount (SAR)")}</th><th class="n">${esc("Adjustment")}</th><th class="n">${esc("VAT amount")}</th></tr></thead><tbody>
    ${BOXES.slice(0,5).map(boxRow).join("")}${tot(6,"Total sales","t6a","t6v")}<tr class="sub"><th></th><th colspan="4">${esc("Purchases")}</th></tr>${BOXES.slice(5).map(boxRow).join("")}${tot(12,"Total purchases","t12a","t12v")}
    <tr><td class="boxno">Box 13</td><td>${esc("Total VAT due for the period")}</td><td colspan="2"></td><td class="n" id="t13"></td></tr>
    <tr><td class="boxno">Box 14</td><td>${esc("Corrections from previous periods (max ±5,000)")} <span id="b14chk"></span></td><td colspan="2"></td><td><input class="num" inputmode="decimal" data-top="b14" value="${esc(r.b14)}" aria-label="Box 14"></td></tr>
    <tr><td class="boxno">Box 15</td><td>${esc("VAT credit carried forward from previous periods")}</td><td colspan="2"></td><td><input class="num" inputmode="decimal" data-top="b15" value="${esc(r.b15)}" aria-label="Box 15"></td></tr>
    <tr class="total"><td class="boxno">Box 16</td><td><span>${esc("Net VAT due (or claimed)")}</span> · <span>${esc("as filed")}</span></td><td colspan="2" class="n" id="t16c"></td><td><input class="num" inputmode="decimal" data-top="b16" value="${esc(r.b16)}" aria-label="Box 16 as filed"></td></tr></tbody></table></div>
   <p class="note">${esc("VAT on reverse-charge imports (Box 9) counts as both output and input VAT on the return, so it is added to total output VAT here. Check this against your filed return.")}</p></section>
  ${card("All periods",`<div id="retsum"></div>`,`<button class="btn sm" data-copy="t-retsum">${esc("Copy table")}</button>`)}`};
function retSummary(C){return `<div class="frame"><table class="tbl" id="t-retsum"><thead><tr><th>${esc("Period")}</th><th>${esc("Filed")}</th><th class="n">${esc("Total sales")}</th><th class="n">${esc("Output VAT")}</th><th class="n">${esc("Total purchases")}</th><th class="n">${esc("Input VAT")}</th><th class="n">Box 13</th><th class="n">${esc("Box 16 recalculated")}</th><th class="n">${esc("Box 16 filed")}</th><th>${esc("Arithmetic")}</th><th>${esc("On time")}</th><th>Box 14</th></tr></thead><tbody>
  ${C.ps.map((p,i)=>{const X=C.rets[i];return `<tr><td>${esc(p.label)}</td><td>${esc(showDate(S.returns[i].filed))}</td>${nc(X.box6)}${nc(X.out)}${nc(X.box12)}${nc(X.inp)}${nc(X.box13)}${nc(X.b16c)}${nc(X.b16)}<td>${X.arith==="ok"?pill("ok","Agrees"):X.arith==="bad"?pill("bad","Filed ≠ recalculated"):pill("none","Not entered")}</td><td>${X.late==="ok"?pill("ok","On time"):X.late==="bad"?pill("bad",L(`${X.lateDays} days late`,`متأخر ${X.lateDays} يوم`)):pill("none","—")}</td><td>${X.b14ok?pill("ok","✓"):pill("bad","Over 5,000")}</td></tr>`}).join("")}
  <tr class="total"><td>${esc("Year")}</td><td></td>${["box6","out","box12","inp","box13","b16c","b16"].map(f=>nc(C.rets.reduce((s,x)=>s+x[f],0))).join("")}<td colspan="3"></td></tr></tbody></table></div>`}
L("Agrees","مطابق");L("Filed ≠ recalculated","المقدم ≠ المعاد احتسابه");L("On time","في الموعد");L("Over 5,000","يتجاوز 5,000");L("Not entered","لم يُدخل");
AFTER.ret=C=>{const k=Math.min(UI.ret.p,C.ps.length-1);
  const refresh=()=>{const C2=compute(),X=C2.rets[k];$("#t6a").textContent=fmt(X.box6);$("#t6v").textContent=fmt([1,2,3,4,5].reduce((s,b)=>s+X.v(b),0));$("#t12a").textContent=fmt(X.box12);$("#t12v").textContent=fmt(X.inp);
    $("#t13").textContent=fmt(X.box13);$("#t16c").innerHTML=`${esc(L("Recalculated","بعد إعادة الاحتساب"))}: ${fmt(X.b16c)} ${X.arith==="ok"?pill("ok","✓"):X.arith==="bad"?pill("bad",L("differs","مختلف")):""}`;$("#b14chk").innerHTML=X.b14ok?"":pill("bad","over limit");$("#retsum").innerHTML=retSummary(C2);renderNav(C2)};
  refresh();document.querySelectorAll("[data-rp]").forEach(b=>b.onclick=()=>{UI.ret.p=+b.dataset.rp;render()});
  const form=document.querySelector(".form");
  form.addEventListener("input",e=>{const el=e.target,r=S.returns[k];if(el.dataset.b)r.b[el.dataset.b][el.dataset.f]=el.value;else if(el.dataset.top)r[el.dataset.top]=el.value;else return;S.example=false;save();refresh()});
  form.addEventListener("paste",e=>{const el=e.target;if(!el.dataset.b)return;const t=e.clipboardData.getData("text");if(!/[\t\n]/.test(t.trim()))return;e.preventDefault();const lines=t.replace(/\r/g,"").trim().split("\n").map(l=>l.split("\t"));
    const fields=["a","j","v"],bi=BOX_IDS.indexOf(+el.dataset.b),fi=fields.indexOf(el.dataset.f);lines.forEach((cells,ri)=>{const b=BOX_IDS[bi+ri];if(!b)return;cells.forEach((v,ci)=>{const f=fields[fi+ci];if(f)S.returns[k].b[b][f]=v===""?"":String(num(v))})});save();render()})};

// ================================================================ reconciliations
R.rsales=C=>`<p class="lead">${esc("For each box: what you declared, what you invoiced, and what you booked in the ledger. ZATCA usually starts here.")}</p>`+C.salesRec.map(x=>{const t=x.rows.reduce((a,r)=>({ret:a.ret+r.ret,reg:a.reg+r.reg,tb:a.tb+r.tb}),{ret:0,reg:0,tb:0}),id="t-rs"+x.b,bad=x.rows.filter(r=>r.s==="bad").length;
 return card(`Box ${x.b} · ${x.cat.replace(/ \(Box \d\)/,"")}`,`<div class="frame"><table class="tbl" id="${id}"><thead><tr><th>${esc("Period")}</th><th class="n">${esc("VAT return")}</th><th class="n">${esc("Sales register")}</th><th class="n">${esc("Trial balance")}</th><th class="n">${esc("Return − register")}</th><th class="n">${esc("Return − TB")}</th><th>${esc("Status")}</th></tr></thead><tbody>
 ${x.rows.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.ret)}${nc(r.reg)}${nc(r.tb)}${dc(r.d1,C.c.tol)}${dc(r.d2,C.c.tol)}<td>${sp(r.s)}</td></tr>`).join("")}
 <tr class="total"><td>${esc("Year")}</td>${nc(t.ret)}${nc(t.reg)}${nc(t.tb)}${dc(t.ret-t.reg,C.c.tol)}${dc(t.ret-t.tb,C.c.tol)}<td></td></tr></tbody></table></div>`,`${bad?pill("bad",L(`${bad} periods`,`${bad} فترة`)):""}<button class="btn sm" data-copy="${id}">${esc("Copy table")}</button>`)}).join("");
R.rrev=C=>{const v=C.rev;return `<p class="lead">${esc("Revenue in the financial statements against total sales declared for the year. ZATCA treats any unexplained excess as undeclared taxable sales.")}</p>
 <div class="grid2">${card("",`<div class="frame"><table class="tbl" id="t-rev"><tbody><tr><td>${esc("Total revenue per trial balance (FS class = Revenue)")}</td>${nc(v.tbRev)}</tr><tr><td>${esc("Less: revenue mapped as out of scope / other income")}</td>${nc(-v.oos)}</tr><tr class="total"><td>${esc("Revenue subject to VAT reporting")}</td>${nc(v.subj)}</tr><tr><td>${esc("Total sales per VAT returns (Box 6, full year)")}</td>${nc(v.retSales)}</tr><tr class="total"><td>${esc("Difference before reconciling items")}</td>${dc(v.rdiff,C.c.tol)}</tr></tbody></table></div>`)}
 <div class="tile hero ${Math.abs(v.unexpl)>C.c.tol?"bad":"ok"}"><span class="t-lab">${esc("Unexplained difference")}</span><span class="t-val big num" id="unexpl">${fmt(v.unexpl)}</span><span class="t-sub">${esc(Math.abs(v.unexpl)>C.c.tol?"Explain or correct before submitting":"Fully reconciled")}</span></div></div>
 ${card("Explained reconciling items",`<p class="note">${esc("Enter each item with the sign that reduces the difference.")}</p><div class="frame"><table class="tbl edit"><thead><tr><th>${esc("Description")}</th><th class="n">${esc("Amount (SAR)")}</th><th></th></tr></thead><tbody>
 ${S.recItems.map((x,i)=>`<tr><td><input class="ri" data-i="${i}" data-f="d" value="${esc(x.d)}" style="min-width:260px"></td><td><input class="ri num" data-i="${i}" data-f="a" inputmode="decimal" value="${esc(x.a)}"></td><td><button class="del" data-ri="${i}" aria-label="Delete item">×</button></td></tr>`).join("")}</tbody></table></div><div class="row"><button class="btn sm" id="addri">${esc("Add item")}</button></div>`)}`};
AFTER.rrev=()=>{document.querySelectorAll(".ri").forEach(el=>el.addEventListener("input",()=>{S.recItems[+el.dataset.i][el.dataset.f]=el.value;save();const C=compute();$("#unexpl").textContent=fmt(C.rev.unexpl);renderNav(C)}));
 document.querySelectorAll("[data-ri]").forEach(b=>b.onclick=()=>{S.recItems.splice(+b.dataset.ri,1);save();render()});$("#addri").onclick=()=>{S.recItems.push({d:"",a:""});save();render()}};
const activeIdx=C=>{const a=C.ps.filter((p,i)=>C.rets[i].entered||C.outRec[i].gl||C.inRec[i].gl||C.outRec[i].reg);return(a.length?a:C.ps.slice(0,3))};
R.rout=C=>{const T=f=>C.outRec.reduce((s,x)=>s+x[f],0),A=activeIdx(C);return `<p class="lead">${esc("Output VAT declared against invoices, the ledger and a 15% recomputation. Box 2 VAT is borne by the State and is left out of the recomputation.")}</p>
 ${card(L("Declared vs invoiced vs ledger","المُقر به مقابل الفواتير مقابل الدفاتر"),columnChart(A.map(p=>p.short),[{name:L("Declared in return","المُقر بها في الإقرار"),c:"s1",values:A.map(p=>C.outRec[p.i].ret)},{name:L("Invoiced (register)","الفواتير (السجل)"),c:"s3",values:A.map(p=>C.outRec[p.i].reg)},{name:L("Booked in ledger","المسجلة في الدفاتر"),c:"s2",values:A.map(p=>C.outRec[p.i].gl)}]))}
 ${card("",`<div class="frame"><table class="tbl" id="t-out"><thead><tr><th>${esc("Period")}</th><th class="n">${esc("Return (incl. RCM)")}</th><th class="n">${esc("Register sales VAT")}</th><th class="n">${esc("Register RCM VAT")}</th><th class="n">${esc("15% × (Box 1 + Box 9)")}</th><th class="n">${esc("GL output VAT")}</th><th class="n">${esc("Return − register")}</th><th class="n">${esc("Return − 15%")}</th><th class="n">${esc("Return − GL")}</th><th>${esc("Status")}</th><th class="n">${esc("Possible under-declaration")}</th></tr></thead><tbody>
 ${C.outRec.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.ret)}${nc(r.rs)}${nc(r.rr)}${nc(r.rc)}${nc(r.gl)}${dc(r.d1,C.c.tol)}${dc(r.d2,C.c.tol)}${dc(r.d3,C.c.tol)}<td>${sp(r.s)}</td>${nc(r.under,r.under>C.c.tol)}</tr>`).join("")}
 <tr class="total"><td>${esc("Year")}</td>${["ret","rs","rr","rc","gl","d1","d2","d3"].map(f=>nc(T(f))).join("")}<td></td>${nc(T("under"),T("under")>C.c.tol)}</tr></tbody></table></div>`,"",)}<div class="row"><button class="btn sm" data-copy="t-out">${esc("Copy table")}</button></div>`};
R.rin=C=>{const T=f=>C.inRec.reduce((s,x)=>s+x[f],0),A=activeIdx(C);return `<p class="lead">${esc("Input VAT claimed against the register and the ledger, and the part ZATCA is likely to disallow (no valid invoice, blocked expense, invalid supplier VAT number).")}</p>
 ${card(L("Claimed vs defensible vs ledger","المخصوم مقابل القابل للدفاع مقابل الدفاتر"),columnChart(A.map(p=>p.short),[{name:L("Claimed in return","المخصومة في الإقرار"),c:"s1",values:A.map(p=>C.inRec[p.i].ret)},{name:L("Defensible","القابلة للدفاع عنها"),c:"s3",values:A.map(p=>C.inRec[p.i].df)},{name:L("Booked in ledger","المسجلة في الدفاتر"),c:"s2",values:A.map(p=>C.inRec[p.i].gl)}]))}
 ${card("",`<div class="frame"><table class="tbl" id="t-in"><thead><tr><th>${esc("Period")}</th><th class="n">${esc("Return (Box 12)")}</th><th class="n">${esc("Register claimed")}</th><th class="n">${esc("Defensible")}</th><th class="n">${esc("At risk")}</th><th class="n">${esc("GL input VAT")}</th><th class="n">${esc("Return − register")}</th><th class="n">${esc("Return − GL")}</th><th>${esc("Status")}</th><th class="n">${esc("Possible over-claim")}</th></tr></thead><tbody>
 ${C.inRec.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.ret)}${nc(r.cl)}${nc(r.df)}${nc(r.rk,r.rk>0)}${nc(r.gl)}${dc(r.d1,C.c.tol)}${dc(r.d2,C.c.tol)}<td>${sp(r.s)}</td>${nc(r.over,r.over>C.c.tol)}</tr>`).join("")}
 <tr class="total"><td>${esc("Year")}</td>${["ret","cl","df","rk","gl","d1","d2"].map(f=>nc(T(f))).join("")}<td></td>${nc(T("over"),T("over")>C.c.tol)}</tr></tbody></table></div><div class="row"><button class="btn sm" data-copy="t-in">${esc("Copy table")}</button></div>`)}
 ${card("Imports: Box 8 and Box 9",`<div class="frame"><table class="tbl" id="t-imp"><thead><tr><th>${esc("Period")}</th><th class="n">${esc("Box 8 VAT (return)")}</th><th class="n">${esc("Customs VAT (register)")}</th><th class="n">${esc("Difference")}</th><th class="n">${esc("Box 9 VAT (return)")}</th><th class="n">${esc("RCM VAT (register)")}</th><th class="n">${esc("Difference")}</th></tr></thead><tbody>
 ${C.inRec.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.b8)}${nc(r.c8)}${dc(r.d8,C.c.tol)}${nc(r.b9)}${nc(r.c9)}${dc(r.d9,C.c.tol)}</tr>`).join("")}</tbody></table></div><p class="note">${esc("Also match Box 8 to ZATCA's customs import data. Customs VAT is deductible only when your company is the importer of record on the Bayan.")}</p>`)}`};
R.rvat=C=>{const T=f=>C.vatRec.reduce((s,x)=>s+x[f],0);return `<p class="lead">${esc(`Proves the ledger VAT liability equals returns filed less payments made, and estimates late-payment penalties up to ${showDate(S.setup.asof)}.`)}</p>
 <div class="tiles four">${tile("Opening VAT liability per ledger:".replace(":",""),`<span class="num">${fmt(C.openLiab)}</span>`)}${tile(L("Paid to ZATCA","المسدد للهيئة"),`<span class="num">${fmt(T("paid"))}</span>`)}${tile(L("Still unpaid","غير مسدد"),`<span class="num">${fmt(Math.max(0,T("outst")))}</span>`,"",T("outst")>C.c.tol?"badv":"")}${tile(L("Late payment penalties","غرامات التأخر في السداد"),`<span class="num">${fmt(T("latePen")+T("unpaidPen"))}</span>`)}</div>
 ${card("",`<div class="frame"><table class="tbl" id="t-vat"><thead><tr><th>${esc("Period")}</th><th class="n">${esc("Net VAT (Box 13 + 14)")}</th><th class="n">${esc("Box 16 filed")}</th><th class="n">${esc("Paid / (refunded)")}</th><th class="n">${esc("Outstanding")}</th><th>${esc("Due")}</th><th>${esc("Filed")}</th><th class="n">${esc("Penalty: paid late")}</th><th class="n">${esc("Penalty: still unpaid")}</th><th class="n">${esc("GL liability")}</th><th class="n">${esc("Expected liability")}</th><th class="n">${esc("Difference")}</th><th>${esc("Status")}</th></tr></thead><tbody>
 ${C.vatRec.map(r=>`<tr><td>${esc(r.p.label)}</td>${nc(r.net)}${nc(r.b16)}${nc(r.paid)}${nc(r.outst,r.outst>C.c.tol)}<td>${esc(showDate(r.p.due))}</td><td>${r.late==="ok"?pill("ok","✓"):r.late==="bad"?pill("bad",L(`${r.lateDays} days late`,`متأخر ${r.lateDays} يوم`)):pill("none","—")}</td>${nc(r.latePen,r.latePen>0)}${nc(r.unpaidPen,r.unpaidPen>0)}${nc(r.gl)}${nc(r.exp)}${dc(r.diff,C.c.tol)}<td>${r.s==="ok"?pill("ok","Agrees"):r.s==="bad"?pill("bad","Investigate"):r.carried?pill("warn",L("Earlier difference carried forward","فرق سابق مُرحّل")):pill("none","No activity")}</td></tr>`).join("")}
 <tr class="total"><td>${esc("Year")}</td>${["net","b16","paid","outst"].map(f=>nc(T(f))).join("")}<td></td><td></td>${nc(T("latePen"))}${nc(T("unpaidPen"))}<td colspan="4"></td></tr></tbody></table></div><p class="note">${esc("Expected liability = opening liability + cumulative (Box 13 + Box 14) − payments dated on or before period end. Late filing (5% to 25% of the tax) and incorrect return (50% of the difference) penalties may also apply.")}</p><div class="row"><button class="btn sm" data-copy="t-vat">${esc("Copy table")}</button></div>`)}`};
L("Paid to ZATCA","المسدد للهيئة");L("Opening VAT liability per ledger","التزام الضريبة الافتتاحي حسب الدفاتر");

// ================================================================ start
window.addEventListener("hashchange",()=>{const h=location.hash.slice(1);if(VIEWS.some(v=>v.id===h))go(h)});
applyLang();$("#nav").setAttribute("aria-label",tr("Sections"));langObserver.observe(document.body,{childList:true,subtree:true,characterData:true});
if(REMOTE){if(HAD_CACHE)sync.state="refreshing";loadRemote()}render();
